' Gambas module file

'
' estru3D
' Software para cálculo de estructuras mediante el método de la rigidez. Calcula estructuras tridimensionales, representa esfuerzos y solicitaciones en apoyos. Gráficas elásticas.
'
' Copyright (C) Ing Martin P Cristia
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA
'

'Declaracion de constantes

Public Const N As Integer = 1
Public Const Qy As Integer = 2
Public Const Qz As Integer = 3
Public Const T As Integer = 4
Public Const My As Integer = 5
Public Const Mz As Integer = 6

Public Const coefgraf As Float = 1.1
Public mucho As Float = 10 ^ 200
Public Const Poco As Float = 1E-5
Public Const reticuladoplano As Integer = 1
Public Const pensando As Integer = 11
Public Const reticuladoespacial As Integer = 2
Public Const MEF As Integer = 5
Public Const serial_number As Integer = 1
Public Const porticoplano As Integer = 3
Public Const porticoespacial As Integer = 4
Public Const magic404 As String = "Estructural-4.1"
Public Const rotula As Integer = 0
Public Const empo As Integer = 1
Public Const magic As String = "Estructural-1.0"
Public Const magic2 As String = "Estructural-2.0"
Public Const magic3 As String = "Estructural-3.0"
Public Const magic4 As String = "Estructural-4.0" ' version 32 bits, distinto formato de cargas
Public Const magic5 As String = "Estructural-5.0" ' version Linux
Public Const magic6 As String = "Estructural-6.0" ' version Linux con handles
Public Const vanterior As Integer = 0
Public Const vsuperior As Integer = 1
Public Const vlateral As Integer = 2
Public Const caballera As Integer = 3
Public Const isometrica As Integer = 4
Public Const impresora As Integer = 1
Public Const pantalla As Integer = 2
Public Const check_nudos As Integer = 1
Public Const check_barras As Integer = 2
Public Const check_apoyos As Integer = 4
Public Const check_datos As Integer = 8
Public Const check_vars As Integer = 16
Public Const modo_design As Integer = 0
Public Const modo_calculo As Integer = 1
Public Const modo_real As Integer = 2
Public Const modo_ayuda As Integer = 3

Public Const tipo_indef As Integer = 0
Public Const tipo_columna As Integer = 1
Public Const tipo_viga As Integer = 2
Public Const tipo_losa As Integer = 3
Public Const tipo_tabique As Integer = 4
Public Const tipo_xxx As Integer = 5

' errores
Public Const error_nudossueltos As Integer = 1
Public Const error_nudosduplicados As Integer = 2
Public Const error_nudosinsuficientes As Integer = 4
Public Const error_barrasinsuficientes As Integer = 8
Public Const error_barrassueltas As Integer = 16
Public Const error_barrassindatos As Integer = 32
Public Const error_apoyosinsuficientes As Integer = 32
Public Const error_rotulas As Integer = 64
Public Const error_nimayor As Integer = 128
Public Const PUNTUAL As Integer = 1
Public Const REPTOT As Integer = 2
Public Const REPpar As Integer = 3
Public Const tem As Integer = 4
Public Const pxy As Integer = 1
Public Const pxz As Integer = 2

Public tipocarga As Integer
Public plano As Integer

'Declaracion de variables de ambiente

Public paso_p As Long
Public paso_q As Long
Public paso_n As Integer
Public paso_t As Long
Public paso_qc As Long

Public paso_pc As Long
Public paso_pe As Long
Public totalqc As Long
Public totalpc As Long
Public totalpe As Long
Public porcentaje As Long 'esto lo paso al C
Public auxiliar1 As String = Space$(1240)

' zooms
'Public rectangulo.x0 As Single, rectangulo.y0 As Single, rectangulo.x1 As Single, rectangulo.y1 As Single

Public Invertir As Boolean = True
Public zooming As Integer
Public anterior_barrita As Integer
Public ZOOMED As Integer
Public use_filter As Integer
Public filter_x0 As Float
Public filter_x1 As Float
Public filter_y0 As Float
Public filter_y1 As Float
Public filter_z0 As Float
Public filter_z1 As Float

Public Struct extremosStruct
    empoempo As String
    empofijo As String
    fijoempo As String
    fijofijo As String
    tensor As String
End Struct

' factores para las unidades
Public pirata As Integer
Public pasolon As Float
Public tipodia As Integer
Public ordmatrig As Integer
Public estructura As Integer

'
Public escribiendo As Integer
Public textgrid As String
Public egc As Integer
Public egr As Integer

Public a_abrir As String
Public vermatriz As Integer
Public viendomatrig As Integer
Public pathproys As String

'Declaracion de variable tipo
'
''================================================================
' Nuevos tipos

Public STLmodel As New Model3d

Public Struct flechatype4
    fy As Float
    fz As Float
End Struct

Public Struct segordtype4    ' son los dos momentos que se ue
    My As Float
    Mz As Float
End Struct

Public Struct settingsSTRUCT
    ' esta estructura debera alojar todos lo parametros relativos a Estru3D y la PC en que corre.

    PasoCalcularEsfuerzos As Long
    PuntosInterpolados As Integer 'los puntos en que interpolo en la grid de(model.losas
    PasoGrid As Integer
    PasoEsf As Long     ' 4 cuantas flechitas por barra
    Pasocargarep As Long                 ' 4 cuantas flechitas por barra
    IntervaloElastica As Integer    '
    formato As String
    formato_datos As String
    lastopen1 As String
    lastopen2 As String
    lastopen3 As String
    lastopen4 As String
    lastopen5 As String
    lenguaje As Integer

    solver As String

End Struct

Public Struct estadoSTRUCT
    usar As Integer
    coef As Float
End Struct

Public Struct flagsSTRUCT
    LogFile As File   ' 0 = cerrado
    LogFileName As String
    Perfil As Integer
    Pausa As Boolean
    PerfilTipo As String
    LogOn As Boolean
    palabra_clave As String
    lenguaje As String
    parar_calculos As Integer
    carga As Integer
    barra As String
    nudo As String
    material As String
    dibujar As Boolean
    Calculando As Boolean
    CalculandoEnvolventes As Boolean
    CalculandoSismos As Boolean
    CalculadoSismos As Boolean
    checked As Boolean ' la uso para no chequearla muchas veces
    ayuda_ok As Boolean
    redibujar As Boolean
    calculo_tipo As Integer
    seccion As String
    dibujado As Boolean
    dibujable As Boolean
    calculado As Boolean
    CalculadoEnvolventes As Boolean
    resultado As Integer
    modo As Integer
    cambios As Boolean
    dibujando As Integer
    ayuda As String
    ayuda_mostrar As Boolean
    Estado As Integer
    ' control del texto en la linea de entrada
    Entrada As String
    EntradaLista As Boolean
    EntradaCancel As Boolean
    asistente_copletado As Integer
    asistente_actual As Integer
    MostrarDespuesCalculo As Integer
    OcultarCargas As Boolean

    estadoAccidental As Integer
    estadoPermanente As Integer

End Struct

Public Struct SismoStruct

    frecuencia As Float
    duracion As Float
    amplitud As Float
    subFrecuencia As Float
    direccion As Float
    dt As Float
    amortiguacion As Float

End Struct

Public setting As New SettingsSTRUCT
Public sisMasas As New Float[]
Public sisFuerzas As New Float[]
Public sisDezplazamientos As New Float[]
Public sisMovimiento As New Float[]

Public sSismo As New SismoStruct

Public flags As New FlagsSTRUCT

'Public extremos as new ExtremosStruct

Public material As New Collection

Public Parametros As New Settings(User.Home &/ ".estru3d/estru3d.conf", "Parametros de Estru3D")

Public Tutoriales As New Settings
Public Mats As New Settings(User.Home &/ ".estru3d/Librerias/materiales.estru3d-lib", "Materiales")

Public FontList As New String[]
Public extremos As New String[5]  ' * 6
Public model As Model

' variables globales de graficos

Public Sub PonerEnCero()
    ' pongo en cero todos los valores de todo lo que hay
    ' Esta rutina deberia llamarse cuando arranca el programa y antes de
    ' crear un proyecto nuevo, y de llamar al asistente. El asistente
    ' automaticamente crea un nuevo proyecto.

    Dim o As Integer, oo As Integer, a As Integer, e As Integer, b As Integer
    Dim hkey As String, resultado As String

    fmain.debuginfo("Poniendo en cero")
    setting.pasocargarep = 20 '
    setting.IntervaloElastica = 10 '
    setting.PasoCalcularEsfuerzos = 25 ' cuantas model.secciones por model.barra se evaluan
    setting.PasoEsf = 20 'cuando dibujo esfuerzos, este es la cantidad de flechitas que grafico
    ordmatrig = 0
    estructura = 0
    clc.gr = 0
    flags.Estado = 1
    escribiendo = 0
    textgrid = ""
    egc = 0
    egr = 0
    tipocarga = 0
    plano = 0
    flags.estadoAccidental = 3
    flags.estadoPermanente = 2
    pasolon = 0
    tipodia = 0
    flags.dibujado = False
    flags.dibujando = False
    flags.calculando = False
    flags.calculado = False
    flags.cambios = False
    'fmain.gEstru.Clear
    flags.modo = 0 ' disenio
    calcular_factores ' esto corrige problemas con los factores

    mats_load2()

End Sub

Public Function barras_coincidentes(Optional modo As Integer = 1) As Integer
    ' esta rutina corrige el problema de barras en el mismo lugar físico
    ' devuelve el total de barras eliminadas

    Dim a As ClsBarra, b As ClsBarra, t As Integer
    Dim bk, ak As String
    ' modo=1 se elimina la segunda barra
    ' modo=2 se suman  los datos de las barras antes de eliminar
    ' modo=3 se promedian

    ' V4  modo es obsoleto porque ahora defino mats y model.secciones

    For Each a In model.barra
        ak = model.barra.Key

        For Each b In model.barra
            bk = model.barra.Key
            If bk = ak Then Continue

            If ((a.ni = b.ni) And (a.nF = b.nF)) Or ((a.ni = b.nf) And (a.nF = b.ni)) Then
                'es coincidente
                t = t + 1
                ' Eleimino la model.barra segun la siguiente prelacion
                'tabique
                'columa
                'viga
                'losa
                'barra simple
                'If (a.ni = 629) And (a.nf = 714) Then Stop

                If b.Invertida Then a.Invertida = True
                If b.tipo = tipo_indef Then
                    model.barra.Remove(bk)
                Else If (b.tipo = tipo_losa) And ((a.tipo = tipo_viga) Or (a.tipo = tipo_tabique)) Then
                    If b.restriccion > 0 Then Stop
                    model.barra.Remove(bk)
                Else If (b.tipo = tipo_viga) And (a.tipo = tipo_tabique) Then
                    model.barra.Remove(bk)
                Else
                    model.barra.Remove(ak)
                    Break
                End If

            End If
        Next

    Next
    flags.cambios = True
    ' y tiene que recalcular
    flags.calculado = False
    fmain.SetStatus
    Debug t

    Return t

End Function

' Public Function ColinealBars(Optional modo As Integer) As Integer
'     ' Look for superposed bars, blend them in such case
'
'     'VERY IMPORTANT,
'
'     Dim a As Integer, b As Integer, Found As Boolean, d As Integer, t As Integer, nt As Integer
'     ' modo=1 se elimina la segunda barra
'     ' modo=2 se suman  los datos de las barras antes de eliminar
'     ' modo=3 se promedian
'
'     'we need to check for unused stuff first
'     Dim b1, b2 As ClsBarra
'
'     If model.barra.Count = 0 Then Return
'
'     e3d.flags.dibujable = False
'
'     a = 1 'first bar
'     Do
'
'         fmain.debugInfo(("Verificando barras colineales") & Format$(a / model.barra.Count, "0%"), True)
'
'         Found = False
'         For b = 1 To e3d.model.nudo.max
'
'             'check if node is in between the bar
'             If modAlgebra.IsBetween(model.nudo[model.barra[a].ni], model.nudo[model.barra[a].nf], model.nudo[b], 0.0005) Then
'
'                 ' we need to split that bar, but only if it's not one of then
'
'                 If b <> barra[a].ni And b <> barra[a].nf Then
'
'                     If modAlgebra.Distancia(model.nudo[model.barra[a].ni], model.nudo[b]) < 0.0005 Then Goto model.nudosJuntos
'                     If modAlgebra.Distancia(model.nudo[model.barra[a].nf], model.nudo[b]) < 0.0005 Then Goto model.nudosJuntos
'
'                     'now we split the bar
'
'                     d = AddBarra(b, barra[a].nF, barra[a].seccion, barra[a].material,, False) 'NO chequear x existentes
'
'                     barra[a].nf = b
'
'                     barra[d].grupo = barra[a].grupo
'                     barra[d].sector = barra[a].sector
'                     barra[d].tipo = barra[a].tipo
'                     barra[d].restriccion = barra[a].restriccion
'                     Found = True
'                     t += 1
'
'                     Break
'
'                 End If
'
'             Endif
'
'         Next
'         If Not Found Then a += 1
'
'     Loop Until a > model.barra.Count
'
'     ' now we need to remove those bars in the same place again
'
'     flags.cambios = True
'     ' y tiene que recalcular
'     flags.calculado = False
'     fmain.debugInfo(("Encontradas ") & Format$(t, "0"), False)
'
'     Return t
'
'     model.nudosJuntos:
'
'     fmain.debugInfo(("Hay model.nudos demasiado juntos, eliminar model.nudos duplicados primero"), False)
'     Return -1
'
' End Function

Public Function ColinealBars2(Optional modo As Integer) As Integer
    ' Look for superposed bars, blend them in such case

    'VERY IMPORTANT,

    Dim a As Integer, Found As Boolean, t As Integer, nt As Integer
    ' modo=1 se elimina la segunda barra
    ' modo=2 se suman  los datos de las barras antes de eliminar
    ' modo=3 se promedian

    'we need to check for unused stuff first
    Dim b1, b2 As ClsBarra, n As ClsNudo
    Dim bt As String

    If model.barra.Count = 0 Then Return

    e3d.flags.dibujable = False

    ' Checking all bars
    For Each b1 In model.barra

        fmain.debugInfo(("Verificando barras colineales") & Format$(b1.Indice / model.barra.Count, "0%"), True)

        Found = False
        For Each n In e3d.model.nudo

            'check if node is in between the bar
            If modAlgebra.IsBetween(e3d.model.nudo[b1.ni].xyz, e3d.model.nudo[b1.nf].xyz, n.XYZ, 0.0005) Then

                ' we need to split that bar, but only if it's not one of then

                If (n = e3d.model.nudo[b1.ni]) Or (n = e3d.model.nudo[b1.nf]) Then Continue

                If modAlgebra.Distancia(model.nudo[b1.ni].xyz, n.XYZ) < 0.0005 Then Goto nudosJuntos
                If modAlgebra.Distancia(model.nudo[b1.nf].xyz, n.XYZ) < 0.0005 Then Goto nudosJuntos

                'now we split the bar

                bt = AddBarra(n.handle, b1.nF, b1.seccion, b1.material,, False) 'NO chequear x existentes

                b1.nf = n.handle

                b2 = model.barra[bt]
                b2.grupo = b1.grupo
                b2.tipo = b1.tipo
                b2.restriccion = b1.restriccion
                Found = True
                t += 1

                'Break

            Endif

        Next
        If Not Found Then a += 1

    Next

    ' now we need to remove those bars in the same place again

    flags.cambios = True
    ' y tiene que recalcular
    flags.calculado = False
    fmain.debugInfo(("Encontradas ") & Format$(t, "0"), False)

    Return t

nudosJuntos:

    fmain.debugInfo(("Hay model.nudos demasiado juntos, eliminar model.nudos duplicados primero"), False)
    Return -1

End Function

Public Sub CorregirNumeracionBarras()

    For Each bar As Clsbarra In model.barra
        If model.nudo[bar.ni].indice > model.nudo[bar.nF].indice Then
            Swap bar.ni, bar.nf

            bar.Invertida = True
        Endif

    Next

End Sub

Public Function cpVal(numero As String) As Float

    Dim p As Integer, separador As String, busco As String
    Dim fPi As Float

    ' Reemplaza las , por . y saca el Val
    fpi = Pi  '3,1415 blablabla

    separador = Mid$(Trim$(Str$(fpi)), 2, 1)
    If separador = "," Then busco = "." Else busco = ","

    Do
        p = InStr(numero, busco)
        If p > 0 Then
            Mid$(numero, p, 1) = separador
        Else
            Exit
        End If
    Loop
    Try Return Val(numero)

End Function

Public Function cargar5(archivo As String) As Integer
    'On Error GoTo quepasoaca

    Dim t As Integer, sinerror As Integer, codigo As Integer
    Dim a As Integer, b As Integer, ok As Boolean, sdk As String
    Dim f As File, mtxt, magia As String, entry As String

    Dim l1 As New ClsLosa
    Dim v1 As New ClsViga
    Dim apoyoU As ClsApoyo
    Dim nudou As ClsNudo
    Dim barrau As ClsBarra
    Dim seccu As ClsSeccion
    Dim cnu As ClsCargaNudo
    Dim cbu As ClsCargaBarra

    sinerror = True
    codigo = True   'supongo todo ok
    magia = Space$(15)

    'Stop
    fmain.debuginfo(("Abriendo archivo ") & archivo)

    If Not Exist(archivo) Then Goto quepasoaca

    f = Open archivo For Read

    If sinerror Then

        Input #f, magiA
        If (magia <> magic5) And (magia <> magic6) Then
            Message.Warning(("Archivo no válido"))
            Return False
        Else
            model.datos.magic = magia
        End If

        Do
            If Eof(f) Then Exit
            Line Input #f, entry
            'If entry <> "" Then Exit
            entry = Trim$(entry)

            Select Case LCase$(utils.getparam(entry, 1))
                Case "nodes"

                    ' nudou.max = CInt(utils.getparam(entry, 2))

                Case "desc"
                    model.datos.descripcion = utils.getparam(entry, 2)
                Case "bars"
                    ' model.barra.Count = CInt(utils.getparam(entry, 2))

                Case "slabs"
                    model.datos.totalplacas = CInt(utils.getparam(entry, 2))
                Case "groups"
                    model.datos.TotalGrupos = CInt(utils.getparam(entry, 2))
                Case "sectors"
                    model.datos.totalSectores = CInt(utils.getparam(entry, 2))
                Case "shapes"
                    ' 2020 no interesa mas este dato
                    ' model.secciones.count = CInt(utils.getparam(entry, 2))

                    ' model.secciones.Resize( model.secciones.count + 1)
                    ' model.secciones.Fill(seccU)

                Case "nloads"
                    model.datos.totalcargasnudo = CInt(utils.getparam(entry, 2))

                Case "bloads"
                    model.datos.totalcargasbarra = CInt(utils.getparam(entry, 2))

                Case "ploads"
                    model.datos.totalcargasplacas = CInt(utils.getparam(entry, 2))
                Case "tloadrep"
                    model.envolventes.repartida = CFloat(utils.getparam(entry, 2))

                Case "restrs"
                    'datos.totalapoyos = CInt(utils.getparam(entry, 2))

                Case "type"
                    model.datos.tipo = CInt(utils.getparam(entry, 2))
                Case "units"

                    model.datos.unidades.long_nombre = utils.getparam(entry, 2)
                    model.datos.unidades.peso_nombre = utils.getparam(entry, 3)
                    model.datos.unidades.ang_nombre = utils.getparam(entry, 4)

                Case Like "nstate*"

                    a = Val(Mid$(utils.getparam(entry, 1), 7))
                    model.estados_nombre[a] = utils.getparam(entry, 2) ' & utils.getparam(entry, 3)

                Case Like "mstate*"

                    a = Val(Mid$(utils.getparam(entry, 1), 7))

                    For b = 1 To 10
                        model.combinacion[a, b] = CFloat(utils.getparam(entry, b + 1))
                    Next

                Case "node"

                    nudou = Null
                    nudou = New ClsNudo ' Punto3d 'nudotype4
                    nudou.handle = CStr(model.nudo.Count + 1)
                    model.nudo.add(nudou, CStr(model.nudo.Count + 1))

                    nudou.x = CFloat(utils.getparam(entry, 2))
                    nudou.y = CFloat(utils.getparam(entry, 3))
                    nudou.z = CFloat(utils.getparam(entry, 4))
                    '.grupo = cint(utils.getparam(entry, 5))
                    '.sector = cint(utils.getparam(entry, 6))
                    'FMain.debugInfo("nudo", .x, .y, .z, .grupo, .sector)

                Case "bar"
                    barrau = Null
                    barrau = New ClsBarra
                    barrau.handle = CStr(model.barra.Count + 1)   ' en este momento .Count es 0

                    barrau.ni = (utils.getparam(entry, 2))
                    barrau.nf = (utils.getparam(entry, 3))
                    barrau.materialText = (utils.getparam(entry, 4))
                    If e3d.material.Exist(utils.getparam(entry, 4)) Then barrau.material = e3d.GetMaterialByName(utils.getparam(entry, 4))
                    If IsNull(barrau.material) Then ' intento encontras el maerial ppor handle
                        barrau.material = e3d.GetMaterialByHandle(utils.getparam(entry, 4))
                    Endif

                    barrau.seccionText = (utils.getparam(entry, 5)) ' 2025 for backwards compat
                    If e3d.model.secciones.Exist(utils.getparam(entry, 5)) Then barrau.seccion = GetSeccionByName(utils.getparam(entry, 5))
                    barrau.restriccion = CInt(utils.getparam(entry, 6))
                    barrau.grupo = CInt(utils.getparam(entry, 7))
                    barrau.sector = CInt(utils.getparam(entry, 8))
                    barrau.tipo = CInt(utils.getparam(entry, 9))
                    barrau.Invertida = -CInt(utils.getparam(entry, 10))
                    barrau.Eje = CInt(utils.getparam(entry, 11))
                    barrau.PosX = CInt(utils.getparam(entry, 12))
                    barrau.PosZ = CInt(utils.getparam(entry, 13))

                    'FMain.debugInfo("barra", .ni, .nf, .material, .seccion, .restriccion, .grupo, .sector)

                    model.barra.Add(barraU, CStr(model.barra.Count + 1))
                    ' TODO aca iria la seccion de Placas
                    ' TODO aca iria la seccion de Grupos
                    ' TODO aca iria la seccion de Sectores

                Case "restr"
                    ' ahora los apoyos pertenecen a los nudous
                    ' debo encontrar el nudou en la Coleccion
                    ' de nudous, que ya esta cargada
                    If model.nudo.Exist(utils.getparam(entry, 2)) Then     ' verifico que el nudou exista

                        model.nudo[utils.getparam(entry, 2)].apoyo = New ClsApoyo

                        model.nudo[utils.getparam(entry, 2)].apoyo.rx = CFloat(utils.getparam(entry, 3))
                        model.nudo[utils.getparam(entry, 2)].apoyo.ry = CFloat(utils.getparam(entry, 4))
                        model.nudo[utils.getparam(entry, 2)].apoyo.rz = CFloat(utils.getparam(entry, 5))
                        model.nudo[utils.getparam(entry, 2)].apoyo.rmx = CFloat(utils.getparam(entry, 6))
                        model.nudo[utils.getparam(entry, 2)].apoyo.rmy = CFloat(utils.getparam(entry, 7))
                        model.nudo[utils.getparam(entry, 2)].apoyo.rmz = CFloat(utils.getparam(entry, 8))

                        'fmain.debugInfo("apoyo", .nudo, .rx, .ry, .rz, .rmx, .rmy, .rmz)

                    End If

                Case "slab"
                    'Print #f, "Slabs", "name", "p1", "p2, " p3 ", " p4 ", "e
                    l1 = Null
                    l1 = New ClsLosa

                    l1.nombre = utils.getparam(entry, 2)
                    l1.numero = CInt(utils.getparam())
                    l1.piso = CInt(utils.getparam())
                    l1.sector = CInt(utils.getparam())
                    l1.Nudo1 = (utils.getparam())
                    l1.Nudo2 = (utils.getparam())
                    l1.Nudo3 = (utils.getparam())
                    l1.Nudo4 = (utils.getparam())
                    l1.d = CFloat(utils.getparam())

                    mtxt = (utils.getparam())

                    If e3d.material.Exist(mtxt) Then l1.material = e3d.GetMaterialByName(mtxt)
                    If IsNull(l1.material) Then ' intento encontras el maerial ppor handle
                        l1.material = e3d.GetMaterialByHandle(mtxt)
                    Endif
                    l1.g = CFloat(utils.getparam())
                    l1.p = CFloat(utils.getparam())
                    l1.alivianado = CFloat(utils.getparam())
                    l1.dxGrid = CFloat(utils.getparam())
                    l1.dzGrid = CFloat(utils.getparam())
                    l1.nxGrid = CFloat(utils.getparam())
                    l1.nzGrid = CFloat(utils.getparam())
                    ' If .alivianado = 0 Then .alivianado = 1

                    model.losasAdd(l1)
                Case "wall"

                    utils.AddStruct(model.tabiques)

                    model.tabiques[model.tabiques.max].nombre = utils.getparam(entry, 2)
                    model.tabiques[model.tabiques.max].numero = CInt(utils.getparam())
                    model.tabiques[model.tabiques.max].piso = CInt(utils.getparam())
                    model.tabiques[model.tabiques.max].sector = CInt(utils.getparam())
                    model.tabiques[model.tabiques.max].Nudo1 = CInt(utils.getparam())
                    model.tabiques[model.tabiques.max].Nudo2 = CInt(utils.getparam())
                    model.tabiques[model.tabiques.max].Nudo3 = CInt(utils.getparam())
                    model.tabiques[model.tabiques.max].Nudo4 = CInt(utils.getparam())
                    model.tabiques[model.tabiques.max].d = CFloat(utils.getparam())
                    mtxt = (utils.getparam())

                    If e3d.material.Exist(mtxt) Then model.tabiques[model.tabiques.max].material = e3d.GetMaterialByName(mtxt)
                    If IsNull(model.tabiques[model.tabiques.max].material) Then ' intento encontras el maerial ppor handle
                        model.tabiques[model.tabiques.max].material = e3d.GetMaterialByHandle(mtxt)
                    Endif
                    model.tabiques[model.tabiques.max].g = CFloat(utils.getparam())
                    model.tabiques[model.tabiques.max].p = CFloat(utils.getparam())

                Case "beam"

                    v1 = Null
                    v1 = New ClsViga

                    v1.nombre = utils.getparam(entry, 2)
                    v1.numero = CInt(utils.getparam(entry, 3))
                    v1.piso = CInt(utils.getparam(entry, 4))
                    v1.sector = CInt(utils.getparam(entry, 5))
                    v1.nudo1 = (utils.getparam(entry, 6))
                    v1.nudo2 = (utils.getparam(entry, 7))
                    v1.seccionTxt = (utils.getparam(entry, 8))
                    v1.g = CFloat(utils.getparam(entry, 9))
                    model.vigas.Add(v1)

                Case "nload"

                    cnu = New ClsCargaNudo
                    nudou[utils.getparam(entry, 2)].cargas.add(cnu)

                    nudou[utils.getparam(entry, 2)].cargas.Last.fx = CFloat(utils.getparam(entry, 3))
                    nudou[utils.getparam(entry, 2)].cargas.Last.fy = CFloat(utils.getparam(entry, 4))
                    nudou[utils.getparam(entry, 2)].cargas.Last.fz = CFloat(utils.getparam(entry, 5))
                    nudou[utils.getparam(entry, 2)].cargas.Last.mx = CFloat(utils.getparam(entry, 6))
                    nudou[utils.getparam(entry, 2)].cargas.Last.my = CFloat(utils.getparam(entry, 7))
                    nudou[utils.getparam(entry, 2)].cargas.Last.mz = CFloat(utils.getparam(entry, 8))
                    nudou[utils.getparam(entry, 2)].cargas.Last.Estado = CInt(utils.getparam(entry, 9))
                    'fmain.debugInfo("Carganudo", .nudo, .fx, .fy, .fz, .mx, .my, .mz, .Estado)

                Case "bload"
                    cbu = New ClsCargaBarra
                    If model.barra.Exist(utils.getparam(entry, 2)) Then
                        model.barra[utils.getparam(entry, 2)].cargas.add(cbu)

                        '.barra = CInt(utils.getparam(entry, 2))
                        model.barra[utils.getparam(entry, 2)].cargas.Last.tipo = CInt(utils.getparam(entry, 3))
                        model.barra[utils.getparam(entry, 2)].cargas.Last.px = CFloat(utils.getparam(entry, 4))
                        model.barra[utils.getparam(entry, 2)].cargas.Last.py = CFloat(utils.getparam(entry, 5))
                        model.barra[utils.getparam(entry, 2)].cargas.Last.pz = CFloat(utils.getparam(entry, 6))
                        model.barra[utils.getparam(entry, 2)].cargas.Last.a = CFloat(utils.getparam(entry, 7))
                        model.barra[utils.getparam(entry, 2)].cargas.Last.b = CFloat(utils.getparam(entry, 8))
                        model.barra[utils.getparam(entry, 2)].cargas.Last.c = CFloat(utils.getparam(entry, 9))
                        model.barra[utils.getparam(entry, 2)].cargas.Last.e = CFloat(utils.getparam(entry, 10)) 'estado

                    End If

                Case "tload"
                    model.trenCargas.Add(CFloat(utils.getparam(entry, 2)))
                    model.trenDistancia.Add(CFloat(utils.getparam(entry, 3)))

                Case "tpathbar"
                    model.camino.Add(CInt(utils.getparam(entry, 2)))
                Case "tstep"
                    model.envolventes.paso_puntuales = CFloat(utils.getparam(entry, 2))
                Case "tloadrep"
                    model.envolventes.repartida = CFloat(utils.getparam(entry, 2))

                Case "shape"
                    seccu = Null
                    seccu = New ClsSeccion

                    seccu.nombre = utils.getparam(entry, 2)
                    seccu.tipo = utils.getparam(entry, 3)
                    seccu.area = CFloat(utils.getparam(entry, 4))
                    seccu.Ip = CFloat(utils.getparam(entry, 5))
                    seccu.iy = CFloat(utils.getparam(entry, 6))
                    seccu.iz = CFloat(utils.getparam(entry, 7))
                    seccu.Wp = CFloat(utils.getparam(entry, 8))
                    seccu.wy = CFloat(utils.getparam(entry, 9))
                    seccu.wz = CFloat(utils.getparam(entry, 10))
                    seccu.a = CFloat(utils.getparam(entry, 11))
                    seccu.b = CFloat(utils.getparam(entry, 12))
                    seccu.c = CFloat(utils.getparam(entry, 13))
                    seccu.d = CFloat(utils.getparam(entry, 14))
                    seccu.e = CFloat(utils.getparam(entry, 15))
                    seccu.f = CFloat(utils.getparam(entry, 16))
                    'fmain.debugInfo("Seccion", .nombre, .tipo, .area, .Ip, .iy, .iz, .Wp, .wy, .wz, .a, .b, .c, .d, .e, .f)

                    seccu.handle = CStr(model.secciones.Count)

                    model.secciones.Add(seccu, CStr(model.secciones.Count))

            End Select
        Loop

    End If
    Close f

    ' 2025 workaround tema model.secciones

    For Each barrau In e3d.model.barra
        If Not barrau.seccion Then

            barrau.seccion = e3d.model.secciones[barrau.seccionText]
        Endif
    Next

    For Each v As ClsViga In e3d.model.vigas
        If Not v.seccion Then

            v.seccion = e3d.model.secciones[v.seccionTxt]
        Endif
    Next

    fmain.debuginfo(("Se abrio exitosamente"))
    fmain.debuginfo(("Tipo de estructura: ") & Str$(model.datos.tipo))
    fmain.debuginfo(("Nodos:") & Str$(e3d.model.nudo.count))
    fmain.debuginfo(("Barras:") & Str$(e3d.model.barra.count))
    fmain.debuginfo(("Cargas:") & Str$(model.datos.totalcargasbarra + model.datos.totalcargasnudo))
    'fmain.debuginfo(("Apoyos:") & Str$(apoyos.count))

    ' pongo lo que cargue en las tablas

    'TODO

saliendos:

    ' grf.ResetMatrizRotacion  'TODO implementar

    'ok = chequeoestructura(check_vars Or check_barras Or check_nudos)

    ' verifico los materiales y los pongo en unitario

    ' For Each barrau In barra
    '
    '     barrau.material = GetMaterialByName("unitario")
    '
    '
    '     barrau.seccion = GetSeccionByName("unitaria")
    '
    '
    '
    ' Next

    Return codigo

quepasoaca:
    'esta es la rutina de errores
    ' debería seleccionar el tipo de error y avisar
    'pero no tengo ganas,asi que voy a devolver el error

    fmain.debuginfo(("Hubo un problema al abrir."), Logger.Error)
    sinerror = False
    codigo = Error
    Return

End Function

Public Function cargar6(archivo As String) As Integer
    'On Error GoTo quepasoaca

    Dim t As Integer, sinerror As Integer, codigo As Integer
    Dim a As Integer, b As Integer, ok As Boolean, sdk As String
    Dim f As File, mtxt, magia As String, entry As String

    Dim t1 As New ClsTabique
    Dim l1 As New ClsLosa
    Dim v1 As New ClsViga
    Dim c1 As ClsColumna
    Dim apoyoU As ClsApoyo
    Dim nudou As ClsNudo
    Dim barrau As ClsBarra
    Dim seccu As ClsSeccion
    Dim cnu As ClsCargaNudo
    Dim cbu As ClsCargaBarra

    Dim hBarra As String

    sinerror = True
    codigo = True   'supongo todo ok
    magia = Space$(15)

    'Stop
    fmain.debuginfo(("Abriendo archivo ") & archivo)

    If Not Exist(archivo) Then Goto quepasoaca

    f = Open archivo For Read

    If sinerror Then

        Input #f, magiA
        If (magia <> magic6) Then
            Message.Warning(("Archivo no válido"))
            Return False
        Else
            model.datos.magic = magia
        End If

        Do
            If Eof(f) Then Exit
            Line Input #f, entry
            'If entry <> "" Then Exit
            entry = Trim$(entry)

            Select Case LCase$(utils.getparam(entry, 1))
                Case "nodes"

                    ' model.nudo.max = CInt(utils.getparam(entry, 2))

                Case "desc"
                    model.datos.descripcion = utils.getparam(entry, 2)
                Case "bars"
                    ' model.barra.Count = CInt(utils.getparam(entry, 2))

                Case "slabs"
                    model.datos.totalplacas = CInt(utils.getparam(entry, 2))
                Case "groups"
                    model.datos.TotalGrupos = CInt(utils.getparam(entry, 2))
                Case "sectors"
                    model.datos.totalSectores = CInt(utils.getparam(entry, 2))
                Case "shapes"
                    ' 2020 no interesa mas este dato
                    ' model.secciones.count = CInt(utils.getparam(entry, 2))

                    ' model.secciones.Resize( model.secciones.count + 1)
                    ' model.secciones.Fill(seccU)

                Case "nloads"
                    model.datos.totalcargasnudo = CInt(utils.getparam(entry, 2))

                Case "bloads"
                    model.datos.totalcargasbarra = CInt(utils.getparam(entry, 2))

                Case "ploads"
                    model.datos.totalcargasplacas = CInt(utils.getparam(entry, 2))
                Case "tloadrep"
                    model.envolventes.repartida = CFloat(utils.getparam(entry, 2))

                Case "restrs"
                    'datos.totalapoyos = CInt(utils.getparam(entry, 2))

                Case "type"
                    model.datos.tipo = CInt(utils.getparam(entry, 2))
                Case "units"

                    model.datos.unidades.long_nombre = utils.getparam(entry, 2)
                    model.datos.unidades.peso_nombre = utils.getparam(entry, 3)
                    model.datos.unidades.ang_nombre = utils.getparam(entry, 4)

                Case Like "nstate*"

                    a = Val(Mid$(utils.getparam(entry, 1), 7))
                    model.estados_nombre[a] = utils.getparam(entry, 2) ' & utils.getparam(entry, 3)

                Case Like "mstate*"

                    a = Val(Mid$(utils.getparam(entry, 1), 7))

                    For b = 1 To 10
                        model.combinacion[a, b] = CFloat(utils.getparam(entry, b + 1))
                    Next

                Case "node"

                    nudou = Null
                    nudou = New ClsNudo ' Punto3d 'nudotype4
                    nudoU.handle = utils.getparam(entry, 2)
                    nudoU.x = CFloat(utils.getparam(entry, 3))
                    nudoU.y = CFloat(utils.getparam(entry, 4))
                    nudoU.z = CFloat(utils.getparam(entry, 5))
                    model.nudo.add(nudou, nudou.handle)

                Case "bar"
                    barrau = Null
                    barrau = New ClsBarra

                    barrau.handle = (utils.getparam(entry, 2))
                    barrau.ni = (utils.getparam(entry, 3))
                    barrau.nf = (utils.getparam(entry, 4))
                    barrau.materialText = (utils.getparam(entry, 5))
                    If e3d.material.Exist(utils.getparam(entry, 5)) Then barrau.material = e3d.GetMaterialByName(utils.getparam(entry, 5))
                    If IsNull(barrau.material) Then ' intento encontras el maerial ppor handle
                        barrau.material = e3d.GetMaterialByHandle(utils.getparam(entry, 5))
                    Endif

                    barrau.seccionText = (utils.getparam(entry, 6)) ' 2025 for backwards compat
                    'If e3d. model.secciones.Exist(utils.getparam(entry, 6)) Then
                    barrau.seccion = GetSeccionByName(utils.getparam(entry, 6))
                    'End If

                    barrau.restriccion = CInt(utils.getparam(entry, 7))
                    barrau.grupo = utils.getparam(entry, 8)
                    barrau.sector = CInt(utils.getparam(entry, 9))
                    barrau.tipo = CInt(utils.getparam(entry, 10))
                    barrau.Invertida = -CInt(utils.getparam(entry, 11))
                    barrau.Eje = CInt(utils.getparam(entry, 12))
                    barrau.PosX = CInt(utils.getparam(entry, 13))
                    barrau.PosZ = CInt(utils.getparam(entry, 14))

                    'FMain.debugInfo("barra", .ni, .nf, .material, .seccion, .restriccion, .grupo, .sector)

                    model.barra.Add(barraU, barrau.handle)
                    ' TODO aca iria la seccion de Placas
                    ' TODO aca iria la seccion de Grupos
                    ' TODO aca iria la seccion de Sectores

                Case "restr"
                    ' ahora los apoyos pertenecen a los model.nudos
                    ' debo encontrar el model.nudo en la Coleccion
                    ' de model.nudos, que ya esta cargada
                    If model.nudo.Exist(utils.getparam(entry, 2)) Then     ' verifico que el model.nudo exista

                        model.nudo[utils.getparam(entry, 2)].apoyo = New ClsApoyo

                        model.nudo[utils.getparam(entry, 2)].apoyo.rx = CFloat(utils.getparam(entry, 3))
                        model.nudo[utils.getparam(entry, 2)].apoyo.ry = CFloat(utils.getparam(entry, 4))
                        model.nudo[utils.getparam(entry, 2)].apoyo.rz = CFloat(utils.getparam(entry, 5))
                        model.nudo[utils.getparam(entry, 2)].apoyo.rmx = CFloat(utils.getparam(entry, 6))
                        model.nudo[utils.getparam(entry, 2)].apoyo.rmy = CFloat(utils.getparam(entry, 7))
                        model.nudo[utils.getparam(entry, 2)].apoyo.rmz = CFloat(utils.getparam(entry, 8))

                        'fmain.debugInfo("apoyo", .nudo, .rx, .ry, .rz, .rmx, .rmy, .rmz)

                    End If

                Case "slab"
                    'Print #f, "Slabs", "name", "p1", "p2, " p3 ", " p4 ", "e
                    l1 = Null
                    l1 = New ClsLosa

                    l1.nombre = utils.getparam(entry, 2)
                    l1.numero = CInt(utils.getparam())
                    l1.handle = utils.getparam()
                    l1.piso = CInt(utils.getparam())
                    l1.sector = CInt(utils.getparam())
                    l1.Nudo1 = (utils.getparam())
                    l1.Nudo2 = (utils.getparam())
                    l1.Nudo3 = (utils.getparam())
                    l1.Nudo4 = (utils.getparam())
                    l1.d = CFloat(utils.getparam())

                    l1.material = e3d.GetMaterialByName((utils.getparam()))

                    l1.g = CFloat(utils.getparam())
                    l1.p = CFloat(utils.getparam())
                    l1.alivianado = CFloat(utils.getparam())
                    l1.dxGrid = CFloat(utils.getparam())
                    l1.dzGrid = CFloat(utils.getparam())
                    l1.nxGrid = CFloat(utils.getparam())
                    l1.nzGrid = CFloat(utils.getparam())
                    ' If .alivianado = 0 Then .alivianado = 1

                    model.losas.Add(l1, l1.Handle)
                Case "wall"
                    t1 = New ClsTabique

                    t1.nombre = utils.getparam(entry, 2)
                    t1.numero = CInt(utils.getparam())
                    t1.Handle = utils.getparam()
                    t1.piso = CInt(utils.getparam())
                    t1.sector = CInt(utils.getparam())
                    t1.Nudo1 = CInt(utils.getparam())
                    t1.Nudo2 = CInt(utils.getparam())
                    t1.Nudo3 = CInt(utils.getparam())
                    t1.Nudo4 = CInt(utils.getparam())
                    t1.d = CFloat(utils.getparam())
                    mtxt = (utils.getparam())

                    If e3d.material.Exist(mtxt) Then t1.material = e3d.GetMaterialByName(mtxt)
                    If IsNull(t1.material) Then ' intento encontras el maerial ppor handle
                        t1.material = e3d.GetMaterialByHandle(mtxt)
                    Endif
                    t1.g = CFloat(utils.getparam())
                    t1.p = CFloat(utils.getparam())

                    model.tabiques.Add(t1, t1.Handle)

                Case "beam"

                    v1 = Null
                    v1 = New ClsViga

                    v1.nombre = utils.getparam(entry, 2)
                    v1.numero = CInt(utils.getparam(entry, 3))
                    v1.handle = utils.getparam(entry, 4)
                    v1.piso = CInt(utils.getparam(entry, 5))
                    v1.sector = CInt(utils.getparam(entry, 6))
                    v1.nudo1 = (utils.getparam(entry, 7))
                    v1.nudo2 = (utils.getparam(entry, 8))
                    v1.seccionTxt = (utils.getparam(entry, 9))
                    v1.g = CFloat(utils.getparam(entry, 10))
                    model.vigas.Add(v1, v1.Handle)

                Case "column"

                    ' Print #f, "Column", c.nombre, c.numero, c.grupo, c.piso, c.sector, c.nudo1, c.nudo2, c.seccion.nombre

                    c1 = New ClsColumna

                    c1.nombre = utils.getparam(entry, 2)
                    c1.numero = CInt(utils.getparam(entry, 3))
                    c1.handle = utils.getparam(entry, 4)
                    c1.piso = CInt(utils.getparam(entry, 5))
                    c1.sector = CInt(utils.getparam(entry, 6))
                    c1.nudo1 = (utils.getparam(entry, 7))
                    c1.nudo2 = (utils.getparam(entry, 8))
                    c1.seccionTxt = (utils.getparam(entry, 9))

                    model.columna.Add(c1, c1.Handle)

                Case "nload"

                    cnu = New ClsCargaNudo
                    model.nudo[utils.getparam(entry, 2)].cargas.add(cnu)

                    model.nudo[utils.getparam(entry, 2)].cargas.Last.fx = CFloat(utils.getparam(entry, 3))
                    model.nudo[utils.getparam(entry, 2)].cargas.Last.fy = CFloat(utils.getparam(entry, 4))
                    model.nudo[utils.getparam(entry, 2)].cargas.Last.fz = CFloat(utils.getparam(entry, 5))
                    model.nudo[utils.getparam(entry, 2)].cargas.Last.mx = CFloat(utils.getparam(entry, 6))
                    model.nudo[utils.getparam(entry, 2)].cargas.Last.my = CFloat(utils.getparam(entry, 7))
                    model.nudo[utils.getparam(entry, 2)].cargas.Last.mz = CFloat(utils.getparam(entry, 8))
                    model.nudo[utils.getparam(entry, 2)].cargas.Last.Estado = CInt(utils.getparam(entry, 9))
                    'fmain.debugInfo("Carganudo", .nudo, .fx, .fy, .fz, .mx, .my, .mz, .Estado)

                Case "bload"
                    cbu = New ClsCargaBarra

                    hbarra = utils.getparam(entry, 2)
                    If model.barra.Exist(hbarra) Then
                        barrau = model.barra[hbarra]
                        barrau.cargas.add(cbu)
                        '.barra = CInt(utils.getparam(entry, 2))
                        barrau.cargas.Last.tipo = CInt(utils.getparam(entry, 3))
                        barrau.cargas.Last.px = CFloat(utils.getparam(entry, 4))
                        barrau.cargas.Last.py = CFloat(utils.getparam(entry, 5))
                        barrau.cargas.Last.pz = CFloat(utils.getparam(entry, 6))
                        barrau.cargas.Last.a = CFloat(utils.getparam(entry, 7))
                        barrau.cargas.Last.b = CFloat(utils.getparam(entry, 8))
                        barrau.cargas.Last.c = CFloat(utils.getparam(entry, 9))
                        barrau.cargas.Last.e = CFloat(utils.getparam(entry, 10)) 'estado

                    End If

                Case "tload"
                    model.trenCargas.Add(CFloat(utils.getparam(entry, 2)))
                    model.trenDistancia.Add(CFloat(utils.getparam(entry, 3)))

                Case "tpathbar"
                    model.camino.Add(CInt(utils.getparam(entry, 2)))
                Case "tstep"
                    model.envolventes.paso_puntuales = CFloat(utils.getparam(entry, 2))
                Case "tloadrep"
                    model.envolventes.repartida = CFloat(utils.getparam(entry, 2))

                Case "shape"
                    seccu = Null
                    seccu = New ClsSeccion

                    seccu.nombre = utils.getparam(entry, 2)
                    seccu.tipo = utils.getparam(entry, 3)
                    seccu.area = CFloat(utils.getparam(entry, 4))
                    seccu.Ip = CFloat(utils.getparam(entry, 5))
                    seccu.iy = CFloat(utils.getparam(entry, 6))
                    seccu.iz = CFloat(utils.getparam(entry, 7))
                    seccu.Wp = CFloat(utils.getparam(entry, 8))
                    seccu.wy = CFloat(utils.getparam(entry, 9))
                    seccu.wz = CFloat(utils.getparam(entry, 10))
                    seccu.a = CFloat(utils.getparam(entry, 11))
                    seccu.b = CFloat(utils.getparam(entry, 12))
                    seccu.c = CFloat(utils.getparam(entry, 13))
                    seccu.d = CFloat(utils.getparam(entry, 14))
                    seccu.e = CFloat(utils.getparam(entry, 15))
                    seccu.f = CFloat(utils.getparam(entry, 16))
                    'fmain.debugInfo("Seccion", .nombre, .tipo, .area, .Ip, .iy, .iz, .Wp, .wy, .wz, .a, .b, .c, .d, .e, .f)

                    seccu.handle = CStr(model.secciones.Count)

                    model.secciones.Add(seccu, CStr(model.secciones.Count))

            End Select
        Loop

    End If
    Close f

    ' 2025 workaround tema model.secciones

    For Each barrau In e3d.model.barra
        If Not barrau.seccion Then

            barrau.seccion = e3d.model.secciones[barrau.seccionText]
        Endif
    Next

    For Each v As ClsViga In e3d.model.vigas
        If Not v.seccion Then

            v.seccion = GetSeccionByName(v.seccionTxt)
        Endif
    Next

    For Each c1 In e3d.model.columna

        c1.seccion = GetSeccionByName(c1.seccionTxt)

    Next

    e3d.ReIndexNodes()

    fmain.debuginfo(("Se abrio exitosamente"))
    fmain.debuginfo(("Tipo de estructura: ") & Str$(model.datos.tipo))
    fmain.debuginfo(("Nodos:") & Str$(e3d.model.nudo.count))
    fmain.debuginfo(("Barras:") & Str$(e3d.model.barra.count))
    fmain.debuginfo(("Cargas:") & Str$(model.datos.totalcargasbarra + model.datos.totalcargasnudo))
    'fmain.debuginfo(("Apoyos:") & Str$(apoyos.count))

    ' pongo lo que cargue en las tablas

    'TODO

saliendos:

    ' grf.ResetMatrizRotacion  'TODO implementar

    'ok = chequeoestructura(check_vars Or check_barras Or check_nudos)

    ' verifico los materiales y los pongo en unitario

    ' For Each barrau In barra
    '
    '     barrau.material = GetMaterialByName("unitario")
    '
    '
    '     barrau.seccion = GetSeccionByName("unitaria")
    '
    '
    '
    ' Next

    Return codigo

quepasoaca:
    'esta es la rutina de errores
    ' debería seleccionar el tipo de error y avisar
    'pero no tengo ganas,asi que voy a devolver el error

    fmain.debuginfo(("Hubo un problema al abrir."), Logger.Error)
    sinerror = False
    codigo = Error
    Return

End Function

Public Function chequeoestructura(tipo As Integer, Optional detallado As Boolean = False, Optional Reparar As Boolean = False) As Integer
    ' lo que voy a ver es:
    '   + si tiene los datos de las barras completos
    '   + si existen los model.nudos de cada barra
    '   + si no hay model.nudos sueltos
    '
    '----------------------------------------------------
    ' PROCESO COMUN PARA TODOS LOS TIPOS

    'On Error Resume Next
    ' TODO Try?
    Dim xxx As Float, ok As Integer, a As Integer, tabien As Boolean, ok2 As Integer
    Dim t1 As Date
    Dim TotalSectores As Integer
    Dim n As ClsNudo, b As ClsBarra
    Dim hNudo, hBarra As String

    ok = 0

    ' ERRORES CRITICOS: los chequeo si o si
    ' chequeo que todas las variables tengan valores correctos o tolerables
    ' valores minimos en las variables almacenadas en 'datos'
    If (model.datos.tipo <= 0) Then model.datos.tipo = 1

    'If model.datos.totalcargasplacas = 0 Then ok = 1

    ' idem opcionales
    If flags.asistente_actual < 0 Then flags.asistente_actual = 0
    If flags.asistente_copletado < 0 Then flags.asistente_copletado = 0

    '
    SetGL

    If (tipo And check_nudos) = check_nudos Then
        ' tiene suficientes?
        If model.nudo.Count < 2 Then
            ok = ok Or error_nudosinsuficientes
            'GoTo salida:
        End If
        ' estan todos ocupador

        a = 0
        For Each n In model.nudo
            hnudo = n.handle
            Inc a
            fmain.debuginfo(("Chequeando model.nudos ") & Format$(a / model.nudo.count, "0%"), True)
            ok2 = False
            For Each b In model.barra
                If b.ni = hNudo Then
                    ok2 = True
                    Break
                End If
                If b.nf = hNudo Then
                    ok2 = True
                    Break
                End If
            Next
            If ok2 = False Then
                ' el model.nudo no esta ocupando
                ok = ok Or error_nudossueltos
                fmain.debuginfo((" model.nudo suelto ") & hNudo, True, True)
                n.Loose = True
                If Reparar Then
                    model.nudo.Remove(model.nudo.Key) '= Null 'EliminarNudo](a)
                    fmain.debuginfo("(eliminado)", False, True)

                Endif
            Else
                n.Loose = False
            End If

        Next

    End If
    fmain.debuginfo(" ")
    If (tipo And check_barras) = check_barras Then

        If model.barra.Count < 1 Then
            ok = ok Or error_barrasinsuficientes
            'GoTo salida:
        End If
        a = 0
        For Each b In model.barra
            Inc a
            fmain.debuginfo(("Chequeando barras: ") & Format$(a / model.barra.Count, "0%"), True)
            'If b.sector > totalsectores Then totalSectores = b.sector
            ' If barra[a].nF < model.barra[a].ni Then
            '
            '     ok = ok Or error_nimayor
            '     fmain.debuginfo((" model.barra con ni>nf ->") & Format$(a, "0"), True, False)
            '     fmain.debuginfo("->", False, False)
            '
            ' End If

            If Not (model.nudo.Exist(b.nF) Or model.nudo.Exist(b.ni)) Then
                ok = ok Or error_barrassueltas
                fmain.debuginfo((" model.barra suelta ->") & n.handle, True, False)
                fmain.debuginfo("->", False, False)
            End If

            If longitud(b) = 0 Then
                ok = ok Or error_barrassueltas
                fmain.debuginfo((" model.barra de largo 0 ->") & b.handle, True, False)
                fmain.debuginfo("->", False, False)
            End If

        Next
    End If
    fmain.debuginfo(" ")
    If (tipo And check_datos) = check_datos Then

        Select Case model.datos.tipo
            Case porticoplano, porticoespacial

                ' ACA SE VERIFICABA LO DE LAS ROTULAS, PERO LO MODIFIQUE PONIENDO UN 1 EN LA DIAGONAL PPAL
                ' For a = 1 To e3d. model.nudo.max
                '     tabien = False
                '     For b = 1 To  model.barra.Count
                '         If barra[b].ni = a Then ' la model.barra tiene el model.nudo considerado
                '             If (model.barra[b].restriccion And 1) = 0 Then tabien = True
                '         Else If barra[b].nF = a Then ' la model.barra tiene el model.nudo considerado
                '             If (model.barra[b].restriccion And 2) = 0 Then tabien = True
                '         End If
                '         If tabien Then Exit 'For
                '     Next
                '     If Not tabien Then
                '         ' verifico que no haya un apoyo empotrado en ese lugar
                '         For b = 1 To e3d.apoyos.max
                '             If apoyos[b].nudo = a Then
                '                 If (apoyos[b].rmx Or apoyos[b].rmy Or apoyos[b].rmz) <> 0 Then tabien = True
                '             End If
                '             If tabien Then Exit 'For
                '         Next
                '
                '         If Not tabien Then ok = ok Or error_rotulas
                '         'GoTo salida:
                '
                '     End If
                ' Next

        End Select

        ' verifico que estén todos los datos de las barras
        If (model.datos.tipo = reticuladoplano) Or (model.datos.tipo = reticuladoespacial) Or (model.datos.tipo = porticoplano) Or (model.datos.tipo = porticoespacial) Then
            For Each b In model.barra
                If (b.seccion.area <= 0) Or (b.material.e <= 0) Then
                    ok = ok Or error_barrassindatos
                    fmain.debuginfo((" model.barra sin datos ") & Format$(a, "0"), True, False)
                    fmain.debuginfo("->", False, False)
                End If
            Next
        End If
        If (model.datos.tipo = porticoplano) Or (model.datos.tipo = porticoespacial) Then
            For Each b In model.barra
                If b.seccion.iz <= 0 Then
                    ok = ok Or error_barrassindatos
                    fmain.debuginfo((" model.barra sin datos ") & Format$(a, "0"), True, False)
                    fmain.debuginfo("->", False, False)
                End If
            Next
        End If
        If (model.datos.tipo = porticoespacial) Then
            For Each b In model.barra
                fmain.debuginfo(("Chequeando parametros: ") & Format$(a / model.barra.Count, "%00.00"), True)
                If (b.seccion.Ip <= 0) Or (b.seccion.iy <= 0) Or (b.seccion.iz <= 0) Or (b.material.g <= 0) Then
                    ok = ok Or error_barrassindatos
                    '
                    fmain.debuginfo((" model.barra sin datos ") & Format$(a, "0"), True, False)
                    fmain.debuginfo("->", False, False)
                End If

            Next

        End If

    End If
salida:
    'Stop
    fmain.debuginfo(("Chequeado en ") & Format$(Timer - t1, "0.00") & "--> " & Str$(ok), True)
    fmain.debuginfo(ErrorString(ok), True)
    fmain.cmbSectorModelo.clear
    fmain.cmbSectorModelo.Add("Todos pisos")
    For a = 1 To totalsectores
        fmain.cmbSectorModelo.Add(Format(a, "##0") & " Piso")

    Next
    If ok = 0 Then flags.dibujable = True
    Return ok

End Function

Public Function esapoyo(hnudo As Integer) As Integer

End Function

Public Function grabar(archivo As String) As Integer

    'Internacionalizacion: grabo y cargo en modo US

    ' Orden en que grabo
    '-------------------
    '   datos
    '   opcionales
    '   model.estados_nombre
    '   model.nudo
    '   barra
    '   auxiliar
    '   cargasnudo
    '   cargasbarra
    '   combinaciones
    '   informe
    '   seciones
    '   apoyos

    'obsoleto
    'If (UCase$(Right$(archivo$, 4)) <> ".CER") And (UCase$(Right$(archivo$, 4)) <> ".CE4") Then archivo$ = archivo$ + ".ce4"

    Dim sinerror As Integer, codigo As Integer, f As File
    Dim a, a1, a2 As Integer
    Dim unNudo As ClsNudo, b As ClsBarra, c As ClsColumna

    Dim cn As ClsCargaNudo, cb As ClsCargaBarra
    'Stop
    fmain.debuginfo(("Guardando el archivo ") & archivo)

    'On Error Goto quepaso
    'TODO implementar control de errores

    sinerror = True
    codigo = True   'supongo todo ok
    f = Open archivo For Write Create
    If sinerror Then
        ' paso al nuevo formato
        model.datos.magic = magic6

        Print #f, model.datos.magic
        Print #f, gb.cr
        Print #f, "WARNING: This file is not meant to edit manually as it can get unreadable."
        Print #f, gb.Cr
        Print #f, "Desc", model.datos.descripcion
        Print #f, "Nodes", model.nudo.Count
        Print #f, "Bars", model.barra.Count
        Print #f, "Slabs", model.losas.Count
        Print #f, "Walls", model.tabiques.Count
        Print #f, "Groups", model.datos.TotalGrupos
        Print #f, "Sectors", model.datos.totalsectores
        Print #f, "Shapes", model.secciones.count
        Print #f, "nLoads", model.datos.totalcargasnudo
        Print #f, "bLoads", model.datos.totalcargasbarra
        Print #f, "pLoads", model.datos.totalcargasplacas
        Print #f, "tLoads", model.trenCargas.Count
        Print #f, "Beams", model.vigas.Count
        Print #f, "Columns", model.columna.Count

        Print #f, "Type", model.datos.tipo

        Print #f, "lSlabs", "name", "numero", "piso", "Sector", "p1", "p2", "p3", "p4", " d", " material", "g", "p", "alivianado"
        For Each l As ClsLosa In model.losas
            Print #f, "Slab", l.nombre, l.numero, l.Handle, l.piso, l.sector, l.Nudo1, l.Nudo2, l.Nudo3, l.Nudo4, CStr(l.d), l.material.nombre, CStr(l.g), CStr(l.p), CStr(l.alivianado), l.dxgrid, l.dzgrid, l.nxgrid, l.nzgrid
        Next

        Print #f, "lWalls", "name", "numero", "piso", "p1", "p2", "p3", "p4", " d", " material"
        For Each t As ClsTabique In model.tabiques
            Print #f, "Wall", t.nombre, t.numero, t.Handle, t.piso, t.sector, t.Nudo1, t.Nudo2, t.Nudo3, t.Nudo4, CStr(t.d), t.material.nombre, CStr(t.g), CStr(t.p)
        Next

        Print #f, "lBeams", "name", "number", "floor", "sector", "p1", "p2", "secc", "g"
        For Each v As ClsViga In model.vigas
            Print #f, "Beam", v.nombre, v.numero, v.Handle, v.piso, v.sector, v.nudo1, v.nudo2, v.seccion.nombre, v.g
        Next

        Print #f, "lColumn", "name", "number", "group", "floor", "sector", "p1", "p2", "secc"
        For Each c In model.columna
            Print #f, "Column", c.nombre, c.numero, c.Handle, c.piso, c.sector, c.nudo1, c.nudo2, c.seccion.nombre
        Next

        Print #f, "Units", model.datos.unidades.long_nombre, model.datos.unidades.peso_nombre, model.datos.unidades.ang_nombre

        For a = 1 To 10
            Print #f, "nState" & Format$(a, "00"), model.estados_nombre[a]
        Next
        ' combinaciones
        For a = 1 To 10
            Print #f, "mState" & Format$(a, "00"),

                For a1 = 1 To 9
                Print #f, CStr(model.combinacion[a, a1]),
                    If Not sinerror Then Goto saliendo
            Next
            Print #f, CStr(model.combinacion[a, 10])

        Next

        ' 2025 ahora voy a guardar primero las model.secciones
        Print #f, "lShapes", "Name", "Type", "Area", "Ipolar", "Iy", "Iz", "Wp", "Wy", "Wz", "a", "b", "c", "d", "e", "f"
        For Each s As ClsSeccion In model.secciones

            Print #f, "Shape", s.nombre, s.tipo, CStr(s.area), CStr(s.Ip), CStr(s.iy), CStr(s.iz), CStr(s.Wp), CStr(s.wy), CStr(s.wz), CStr(s.a), CStr(s.b), CStr(s.c), CStr(s.d), CStr(s.e), CStr(s.f)

        Next

        Print #f, "lNodes", "X", "Y", "Z", "Group", "Sector"
        For Each unNudo In model.nudo

            Print #f, "Node", unnudo.handle, CStr(unnudo.x), CStr(unnudo.y), CStr(unnudo.z)

        Next
        Print #f, "lBars", "handle", "Ni", "Nf", "Mat", "Shape", "Restr", "Group", "Sector", "Tipo", "Inv", "Eje", "PosX", "PosY"
        For Each b In model.barra

            Print #f, "Bar", b.handle, b.ni, b.nf, b.material.nombre, b.seccion.nombre, b.restriccion, b.grupo, b.sector, b.tipo, CInt(b.Invertida), b.Eje, b.PosX, b.posZ

            If Not sinerror Then Goto saliendo
        Next

        ' TODO aca iria la seccion de Placas
        ' TODO aca iria la seccion de Grupos
        ' TODO aca iria la seccion de Sectores
        Print #f, "lRestr", "Node", "rX", "rY", "rZ", "rmX", "rmY", "rmZ"
        For Each unNudo In model.nudo 'a = 0 To e3d.apoyos.max
            If Not IsNull(unnudo.apoyo) Then

                Print #f, "Restr", unnudo.handle, unnudo.apoyo.rx, unnudo.apoyo.ry, unnudo.apoyo.rz, unnudo.apoyo.rmx, unnudo.apoyo.rmy, unnudo.apoyo.rmz ', un model.nudo.apoyo.mx, un model.nudo.apoyo.My, un model.nudo.apoyo.Mz, un model.nudo.apoyo.cex, un model.nudo.apoyo.cey, un model.nudo.apoyo.cez, un model.nudo.apoyo.cefix, un model.nudo.apoyo.cefiy, un model.nudo.apoyo.cefiz, un model.nudo.apoyo.efix, un model.nudo.apoyo.efiy, un model.nudo.apoyo.efiz, un model.nudo.apoyo.mfix, un model.nudo.apoyo.mfiy, un model.nudo.apoyo.mfiz

            End If

            If Not sinerror Then Goto saliendo
        Next

        Print #f, "lnLoads", "Node", "Fx", "Fy", "Fz", "Mx", "My", "Mz", "State"
        For Each unNudo In model.nudo ' a = 1 To model.datos.totalcargasnudo
            For Each cn In unnudo.cargas

                Print #f, "nLoad", unnudo.handle, CStr(cn.fx), CStr(cn.fy), CStr(cn.fz), CStr(cn.mx), CStr(cn.my), CStr(cn.mz), cn.Estado

            Next

        Next

        Print #f, "lbLoads", "Bar", "Type", "Px", "Py", "Pz", "a", "b", "c", "State"
        For Each b In model.barra ' a = 1 To model.datos.totalcargasbarra
            For Each cb In b.cargas

                ' no grabo las combinaciones porque se recalculan al cargar
                If cb.e <= 10 Then Print #f, "bLoad", b.handle, cb.tipo, CStr(cb.px), CStr(cb.py), CStr(cb.pz), CStr(cb.a), CStr(cb.b), CStr(cb.c), cb.e 'estado

            Next
        Next

        Print #f, "tLoadRep", CStr(model.envolventes.repartida)  ' TODO ubicar esto en el lugar correspondiente
        Print #f, "tStep", model.envolventes.paso_puntuales
        Print #f, "tLoads", "tLoad", "tDistance"
        For a = 1 To model.trenCargas.Count

            Print #f, "tLoad", CStr(model.trenCargas[a - 1]), CStr(model.trenDistancia[a - 1])

        Next

        ' cargo el camino del tren
        Print #f, "tPathBars", "tBar"

        For a = 1 To model.Camino.Count

            Print #f, "tPathBar", CStr(model.camino[a - 1])

        Next

        flags.cambios = False

    Else    'o sea que ni pudo abrir el archivo

        Goto saliendo

    End If
    Close f
    fmain.debuginfo(("Se guardo con exito"))

    Goto saliendo

quepaso:
    'esta es la rutina de errores
    ' debería seleccionar el tipo de error y avisar
    'pero no tengo ganas,asi que voy a devolver el error

    sinerror = False
    codigo = Error
    'Resume Next 'TODO implementar
saliendo:
    Return codigo

End Function

Public Function longitud(b As ClsBarra) As Float
    ' devuelve la longitud de la barra

    ' en caso de no existir alguno de los model.nudos, la siguiente instruccion dara error
    Try Return (((model.nudo[b.nF].x - model.nudo[b.ni].x) ^ 2 + (model.nudo[b.nF].y - model.nudo[b.ni].y) ^ 2 + (model.nudo[b.nF].z - model.nudo[b.ni].z) ^ 2)) ^ 0.5
    Return 0

End Function

Public Function lx(bar As ClsBarra) As Float

    Try Return model.nudo[bar.nF].x - model.nudo[bar.ni].x
    Return 0

End Function

Public Function ly(bar As ClsBarra) As Float

    Try Return model.nudo[bar.nF].y - model.nudo[bar.ni].y
    Return 0

End Function

Public Function lz(bar As ClsBarra) As Float

    Try Return model.nudo[bar.nF].z - model.nudo[bar.ni].z
    Return 0

End Function

Public Sub no_escribe_mas()

    escribiendo = False
    textgrid = ""
    egr = 0
    egc = 0

End Sub

Public Function nudos_dobles(Optional tol As Float = 10e-5) As Integer
    ' esta rutina corrige el problema de model.nudos en el mismo lugar físico

    Dim a As Integer, b As Integer, c As Integer, d As Integer, t As Integer

    a = 0
    For Each nudo1 As ClsNudo In model.nudo

        For Each nudo2 As ClsNudo In model.nudo
            If nudo1.handle = nudo2.handle Then Continue
            If Abs(nudo1.x - nudo2.x) < tol And Abs(nudo1.Y - nudo2.Y) < tol And Abs(nudo1.z - nudo2.z) < tol Then
                ' esta es la rutina que reemplaza los valores en el array barras
                ' 1-debo eliminar el model.nudo b de todas la barras y reemplazarlo por el a

                For Each bar As ClsBarra In model.barra
                    '1
                    If bar.ni = nudo1.handle Then bar.ni = nudo2.handle
                    If bar.nF = nudo1.handle Then bar.nF = nudo2.handle

                Next

                model.nudo.Remove(nudo1.handle)

            End If
        Next
    Next

    flags.cambios = True
    ' y tiene que recalcular
    flags.calculado = False

    fmain.SetStatus
    Return t

End Function

Public Sub dibujable()
    ' Verifica si la estructura se puede dibujar y llama a setstatus

    Dim a As Integer

    If e3d.model.graficos.cambios Then
        If chequeoestructura(check_barras Or check_nudos) = 0 Then
            flags.dibujable = True
            e3d.model.graficos.cambios = False
        Else
            ' si no la puedo dibujar, es que hay cambios
            flags.dibujable = False
            flags.dibujado = False
            e3d.model.graficos.cambios = True

        End If
    End If

End Sub

Public Sub escalar()

    Dim a As Integer, b As Integer, Dyz As Float
    Dim unaBarra As ClsBarra, unNudo As ClsNudo
    ' Calculo las escalas de los esfuerzos
    ' obtengo los máximos genereales

    '[pero primero pongo en cero]
    e3d.model.graficos.maxMz = 0
    e3d.model.graficos.maxMy = 0
    e3d.model.graficos.maxT = 0
    e3d.model.graficos.maxQy = 0
    e3d.model.graficos.maxN = 0
    e3d.model.graficos.maxQz = 0

    'Stop
    e3d.model.graficos.escala_esf = 0
    e3d.model.graficos.ESCmz = 1
    e3d.model.graficos.ESCmy = 1
    e3d.model.graficos.ESCt = 1
    e3d.model.graficos.ESCqy = 1
    e3d.model.graficos.ESCn = 1
    e3d.model.graficos.ESCqz = 1

    For Each unaBarra In model.barra ' a = 1 To  model.barra.Count

        If Abs(unabarra.EsfExtBar.maxMz) > e3d.model.graficos.maxMz Then e3d.model.graficos.maxMz = Abs(unabarra.EsfExtBar.maxMz)
        If Abs(unabarra.EsfExtBar.maxMy) > e3d.model.graficos.maxMy Then e3d.model.graficos.maxMy = Abs(unabarra.EsfExtBar.maxMy)
        If Abs(unabarra.EsfExtBar.maxT) > e3d.model.graficos.maxT Then e3d.model.graficos.maxT = Abs(unabarra.EsfExtBar.maxT)
        If Abs(unabarra.EsfExtBar.maxQy) > e3d.model.graficos.maxQy Then e3d.model.graficos.maxQy = Abs(unabarra.EsfExtBar.maxQy)
        If Abs(unabarra.EsfExtBar.maxN) > e3d.model.graficos.maxN Then e3d.model.graficos.maxN = Abs(unabarra.EsfExtBar.maxN)
        If Abs(unabarra.EsfExtBar.maxQz) > e3d.model.graficos.maxQz Then e3d.model.graficos.maxQz = Abs(unabarra.EsfExtBar.maxQz)

        If Abs(unabarra.EsfExtBar.minMz) > e3d.model.graficos.maxMz Then e3d.model.graficos.maxMz = Abs(unabarra.EsfExtBar.minMz)
        If Abs(unabarra.EsfExtBar.minMy) > e3d.model.graficos.maxMy Then e3d.model.graficos.maxMy = Abs(unabarra.EsfExtBar.minMy)
        If Abs(unabarra.EsfExtBar.minT) > e3d.model.graficos.maxT Then e3d.model.graficos.maxT = Abs(unabarra.EsfExtBar.minT)
        If Abs(unabarra.EsfExtBar.minQy) > e3d.model.graficos.maxQy Then e3d.model.graficos.maxQy = Abs(unabarra.EsfExtBar.minQy)
        If Abs(unabarra.EsfExtBar.minN) > e3d.model.graficos.maxN Then e3d.model.graficos.maxN = Abs(unabarra.EsfExtBar.minN)
        If Abs(unabarra.EsfExtBar.minQz) > e3d.model.graficos.maxQz Then e3d.model.graficos.maxQz = Abs(unabarra.EsfExtBar.minQz)

    Next
    If e3d.model.graficos.escala_esf < e3d.model.graficos.maxMz Then e3d.model.graficos.escala_esf = e3d.model.graficos.maxMz
    If e3d.model.graficos.escala_esf < e3d.model.graficos.maxMy Then e3d.model.graficos.escala_esf = e3d.model.graficos.maxMy
    If e3d.model.graficos.escala_esf < e3d.model.graficos.maxT Then e3d.model.graficos.escala_esf = e3d.model.graficos.maxT
    If e3d.model.graficos.escala_esf < e3d.model.graficos.maxQy Then e3d.model.graficos.escala_esf = e3d.model.graficos.maxQy
    If e3d.model.graficos.escala_esf < e3d.model.graficos.maxN Then e3d.model.graficos.escala_esf = e3d.model.graficos.maxN
    If e3d.model.graficos.escala_esf < e3d.model.graficos.maxQz Then e3d.model.graficos.escala_esf = e3d.model.graficos.maxQz
    If e3d.model.graficos.escala_esf = 0 Then e3d.model.graficos.escala_esf = 1

    ' el maximo esf sera la mitad de la model.barra mas corta
    e3d.model.graficos.escala_esf = (e3d.model.graficos.barra_larga * 0.5 + e3d.model.graficos.barra_corta * 0.5 + e3d.model.graficos.largo_estructura * 0.25) / 3 / e3d.model.graficos.escala_esf

    ' ahora lo de la elastica
    e3d.model.graficos.FactorFlecha = 0
    For Each unNudo In model.nudo '  a = 1 To e3d. model.nudo.max
        If e3d.model.graficos.FactorFlecha < Sqr(unnudo.dezplazamientos.dz ^ 2 + unnudo.dezplazamientos.dy ^ 2 + unnudo.dezplazamientos.dx ^ 2) Then e3d.model.graficos.FactorFlecha = Sqr(unnudo.dezplazamientos.dz ^ 2 + unnudo.dezplazamientos.dy ^ 2 + unnudo.dezplazamientos.dx ^ 2)
    Next

    ' que pasa si todos los model.nudos son apoyos?
    For Each unNudo In model.nudo '  a = 1 To e3d. model.nudo.max
        If e3d.model.graficos.FactorFlecha < Sqr(unnudo.dezplazamientos.dfiy ^ 2 + unnudo.dezplazamientos.dfiz ^ 2) / 2 Then
            e3d.model.graficos.FactorFlecha = Sqr(unnudo.dezplazamientos.dfiz ^ 2 + unnudo.dezplazamientos.dfiy ^ 2) / 2

        End If
    Next

    'pero si son todos apoyos, y ademas son todos empotramientos
    If e3d.model.graficos.FactorFlecha = 0 Then
        For Each aBar As ClsBarra In model.barra
            clc.generar_elastica(aBar)
            fmain.debugInfo(("Generando elastica ") & Format$(aBar.indice / model.barra.count, "0.00%"), True)
            dyz = Sqr(model.vectorE[e3d.setting.IntervaloElastica / 2].Y ^ 2 + model.vectorE[e3d.setting.IntervaloElastica / 2].z ^ 2)

            If e3d.model.graficos.FactorFlecha < dyz * longitud(aBar) / 2 Then
                e3d.model.graficos.FactorFlecha = dyz * longitud(aBar) / 2

            End If

        Next

    Endif

    If e3d.model.graficos.FactorFlecha < 1E-40 Then e3d.model.graficos.FactorFlecha = 1
    If e3d.model.graficos.FactorFlecha > 1E+40 Then e3d.model.graficos.FactorFlecha = 1

    ' ahora lo relaciono con la model.barra mas corta
    e3d.model.graficos.FactorFlecha = e3d.model.graficos.barra_larga * 0.05 / e3d.model.graficos.FactorFlecha

End Sub

Public Sub Check_consistencia()
    ' Esta rutina verifica las constantes en datos, opciones, dibujar, etc
    ' y reemplaza valores si es necesario.
    'DATOS

End Sub

Public Sub SetStatusHTM()
    ' ' para indicar el estado de la estructura
    '
    ' Dim a As Integer, ok As Integer, ok2 As Integer, nF As String, nfo As String, er As String
    ' Dim t As Long
    '
    ' nF = Application.Path &/ "/hlp" &/ flags.lenguaje &/ "status.mod"
    ' nFo = User.Home &/ ".estru3d/status.htm"
    '
    ' Try Kill nfo
    ' Copy nf To Nfo
    '
    ' If model.datos.proyecto <> "" Then
    '     ok2 = utils.file_replace(nfo, "__archivo", model.datos.proyecto)
    ' Else
    '     ok2 = utils.file_replace(nfo, "__archivo", "[no definido]")
    ' End If
    ' If Left$(model.datos.descripcion, 1) = Chr$(0) Then
    '     ok2 = utils.file_replace(nFo, "__descripcion", "[no definido]")
    ' Else
    '     ok2 = utils.file_replace(nFo, "__descripcion", model.datos.descripcion)
    ' End If
    ' ok2 = utils.file_replace(nFo, "__totalnudos", Str$(e3d. model.nudo.max))
    ' ok2 = utils.file_replace(nFo, "__totalbarras", Str$( model.barra.Count))
    '
    ' ok2 = utils.file_replace(nFo, "__cargasbarra", Str$(model.datos.totalcargasbarra))
    ' ok2 = utils.file_replace(nFo, "__cargasnudo", Str$(model.datos.totalcargasnudo))
    ' ok2 = utils.file_replace(nFo, "__apoyos", Str$(e3d.apoyos.count))
    ' ok2 = utils.file_replace(nFo, "__secciones", Str$( model.secciones.count))
    ' ok2 = utils.file_replace(nFo, "__materiales", Str$(material_count()))
    ' Select Case model.datos.tipo
    '     Case 1
    '         ok2 = utils.file_replace(nFo, "__tipo", ("Reticulado plano"))
    '     Case 3
    '         ok2 = utils.file_replace(nFo, "__tipo", ("Portico plano"))
    '     Case 2
    '         ok2 = utils.file_replace(nFo, "__tipo", ("Reticulado espacial"))
    '     Case 4
    '         ok2 = utils.file_replace(nFo, "__tipo", ("Portico espacial"))
    '     Case Else
    '         ok2 = utils.file_replace(nFo, "__tipo", ("[no definido]"))
    ' End Select
    '
    ' For a = 1 To 8
    '     t = t + cargasnudo_count(a)
    ' Next
    '
    ' ok2 = utils.file_replace(nFo, "__cargasnudo", Str$(t))
    '
    ' ok = chequeoestructura(check_nudos Or check_barras Or check_datos Or check_apoyos)
    ' ' error_nudossueltos = 1, error_nudosduplicados = 2, error_nudosinsuficientes = 4
    ' ' error_barrasinsuficientes = 8, error_barrassueltas = 16, error_barrassindatos = 32
    ' ' error_apoyosinsuficientes = 32, error_rotulas = 64 ', error_barrassindatos = 32
    ' t = 1 ' problemas
    ' If ok <> 0 Then
    '     If (ok And error_nudossueltos) = error_nudossueltos Then
    '         ok2 = utils.file_replace(nFo, "__problemas" & Format$(t, "0"), (" - Hay model.nudos a los que no llegan barras."))
    '         t = t + 1
    '     End If
    '     If (ok And error_nudosduplicados) = error_nudosduplicados Then
    '         er = ("- Hay model.nudos en la misma posición.")
    '         ok2 = utils.file_replace(nFo, "__problemas" & Format$(t, "0"), er)
    '         t = t + 1
    '     End If
    '     If (ok And error_nudosinsuficientes) = error_nudosinsuficientes Then
    '         er = ("- No hay model.nudos suficientes.")
    '         ok2 = utils.file_replace(nFo, "__problemas" & Format$(t, "0"), er)
    '         t = t + 1
    '     End If
    '     If (ok And error_barrasinsuficientes) = error_barrasinsuficientes Then
    '         er = ("- Barras insuficientes.")
    '         ok2 = utils.file_replace(nFo, "__problemas" & Format$(t, "0"), er)
    '         t = t + 1
    '     End If
    '     If (ok And error_nimayor) = error_nimayor Then
    '         er = ("- Hay barras con el model.nudo inicial mayor que el final.")
    '         ok2 = utils.file_replace(nFo, "__problemas" & Format$(t, "0"), er)
    '         t = t + 1
    '     End If
    '
    '     If (ok And error_barrassueltas) = error_barrassueltas Then
    '         er = ("- Barras no tienen los model.nudos definidos.")
    '         ok2 = utils.file_replace(nFo, "__problemas" & Format$(t, "0"), er)
    '         t = t + 1
    '     End If
    '     If (ok And error_barrassindatos) = error_barrassindatos Then
    '         er = ("- Barras no tienen los datos definidos.")
    '         ok2 = utils.file_replace(nFo, "__problemas" & Format$(t, "0"), er)
    '         t = t + 1
    '     End If
    '     If (ok And error_rotulas) = error_rotulas Then
    '         er = ("- Hay rótulas que generan un mecanismo.")
    '         ok2 = utils.file_replace(nFo, "__problemas" & Format$(t, "0"), er)
    '         t = t + 1
    '     End If
    ' Else
    '     ok2 = utils.file_replace(nFo, "__problemas1", ("No hay problemas que informar. Puede calcularse."))
    '     t = t + 1
    ' End If
    ' For a = t To 6
    '     ok2 = utils.file_replace(nFo, "__problemas" & Format$(a, "0"), " ")
    ' Next

End Sub

Public Function cargasnudo_count(e As Integer) As Long

    ' devuelve la cantidad de cargas en model.nudo para ese estado
    Dim a As Integer, b As Long
    Dim n As ClsNudo

    For Each n In model.nudo 'a = 0 To cargas model.nudo.Count - 1
        For a = 0 To n.cargas.Max
            If n.cargas[a].Estado = e Then
                If n.cargas[a].fx <> 0 Then b = b + 1
                If n.cargas[a].fy <> 0 Then b = b + 1
                If n.cargas[a].fz <> 0 Then b = b + 1
                If n.cargas[a].mx <> 0 Then b = b + 1
                If n.cargas[a].My <> 0 Then b = b + 1
                If n.cargas[a].Mz <> 0 Then b = b + 1
            End If
        Next
    Next
    Return b

End Function

Public Sub mats_save()
    ' guarda los materiales

    Dim f As File, paso As Integer, a As Integer
    'On Error GoTo nopude1:

    paso = 1
    fmain.debuginfo(("Guardando tabla de materiales"))

    'f = Open App.Path & "\\material.lib" For Write
    f = Open User.Home &/ ".estru3d" &/ "Librerias/material.lib" For Create
    For a = 1 To 20
        ' paso todo a mis unidades [ver mats_load]
        material[a].e = material[a].e / model.datos.unidades.factorEG
        material[a].g = material[a].g / model.datos.unidades.factorEG
        material[a].fluencia = material[a].fluencia / model.datos.unidades.factorEG
        material[a].densidad = material[a].densidad / model.datos.unidades.factorDEN
        Write #f, material[a] As MaterialSTRUCT
    Next
    Close f

    Return

nopude1:
    'MsgBox("No puede grabarse la libreria de materiales.")
    'TODO

    Return

End Sub

' Public Sub mats_load()
'     ' carga la tabla de materiales
'
'     Dim f As File, paso As Integer, a As Integer, nnn As String
'     'On Error Goto nopude1:
'     Dim matU As New MaterialSTRUCT
'
'     paso = 1
'     material.clear
'
'     ' cargo el material cero
'
'     matu = Null
'     matu = New MaterialSTRUCT
'     matu.nombre = ("Unitario")
'     matu.densidad = 1
'     matu.e = 1
'     matu.g = 1
'     matu.fluencia = 1
'
'     material.Add(matu)
'     nnn = User.Home &/ ".estru3d/Librerias/material.estru3d-lib"
'     fmain.debuginfo(("Cargando tabla de materiales") & nnn)
'     f = Open nnn For Read
'
'     For a = 1 To 20
'         matu = Read #f As MaterialSTRUCT  ' what a sintax, Benoit!
'         material.Add(matu)
'         matu = Null
'         matu = New MaterialSTRUCT
'
'         ' E , G y Fluencia en ton/m2
'         ' Densidad en ton/m3
'         ' Los factores multiplican estas unidades para llevarlas a las
'         ' del usuario
'         material[a].e = material[a].e * model.datos.unidades.factorEG
'         material[a].g = material[a].g * model.datos.unidades.factorEG
'         material[a].fluencia = material[a].fluencia * model.datos.unidades.factorEG
'         material[a].densidad = material[a].densidad * model.datos.unidades.factorDEN
'     Next
'     Close f
'
'     Return
'
' nopude1:
'     'MsgBox "No puede abrirse la libreria de materiales."
'
' End Sub

Public Sub mats_load2()
    ' using params component

    Dim paso As Integer, a As Integer, nnn As String
    Dim matU As New ClsMaterial

    paso = 1
    material.clear

    ' cargo el material cero

    matu = Null
    matu = New ClsMaterial
    matu.nombre = ("Unitario")
    matu.densidad = 1
    matu.e = 1
    matu.g = 1
    matu.fluencia = 1
    matu.handle = "0"

    material.Add(matu, matu.nombre)

    fmain.debuginfo(("Cargando tabla de materiales") & nnn)

    For a = 1 To 20
        matu = Null
        matu = New ClsMaterial
        matu.handle = CStr(a)
        matu.nombre = Replace(Mats["Material" & Format$(a, "0") & "/Name", "<unnamed>"], " ", "_")
        matu.e = Mats["Material" & Format$(a, "0") & "/E", "1"]
        matu.g = Mats["Material" & Format$(a, "0") & "/G", "1"]
        matu.fluencia = Mats["Material" & Format$(a, "0") & "/F", "1"]
        matu.densidad = Mats["Material" & Format$(a, "0") & "/D", "1"]

        ' E , G y Fluencia en kilo/cm2
        ' Densidad en kilo/m3
        ' Los factores multiplican estas unidades para llevarlas a las
        ' del usuario
        matu.e *= model.datos.unidades.factorEG
        matu.g *= model.datos.unidades.factorEG
        matu.fluencia *= model.datos.unidades.factorEG
        matu.densidad *= model.datos.unidades.factorDEN
        material.Add(matu, matu.nombre)

    Next

    Return

nopude1:
    'MsgBox "No puede abrirse la libreria de materiales."

End Sub

Public Sub calcular_factores()
    ' calcula los factores de las unidades
    ' Primero las pongo en uno

    model.datos.unidades.factorEG = 1
    model.datos.unidades.factorDEN = 1
    model.datos.unidades.factorSUP = 1
    model.datos.unidades.factorLONG = 1
    fmain.debuginfo(("Calculando los factores de las unidades"))

    'Stop
    Select Case LCase$(model.datos.unidades.peso_nombre)
        Case "tons"
            model.datos.unidades.factorEG = model.datos.unidades.factorEG / 1000
            model.datos.unidades.factorDEN = model.datos.unidades.factorDEN / 1000

        Case "kilo"
            ' nada!!! porque es default
        Case "pndf"
            model.datos.unidades.factorEG = model.datos.unidades.factorEG * 2.2046
            model.datos.unidades.factorDEN = model.datos.unidades.factorDEN * 2.2046
        Case "knwt"
            model.datos.unidades.factorEG = model.datos.unidades.factorEG * 0.00980665
            model.datos.unidades.factorDEN = model.datos.unidades.factorDEN * 0.00980665
        Case Else
            model.datos.unidades.peso_nombre = "kilo"
    End Select

    Select Case LCase$(model.datos.unidades.long_nombre)
        Case "metr"

            model.datos.unidades.factorLONG = model.datos.unidades.factorLONG
            model.datos.unidades.factorSUP = model.datos.unidades.factorSUP
            model.datos.unidades.factorEG = model.datos.unidades.factorEG * 100 ^ 2

        Case "cent"
            model.datos.unidades.factorLONG = model.datos.unidades.factorLONG * 100
            model.datos.unidades.factorSUP = model.datos.unidades.factorSUP * 100 ^ 2
            model.datos.unidades.factorEG = 1  'default
            model.datos.unidades.factorDEN = model.datos.unidades.factorDEN / 100 ^ 3
        Case "inch"
            model.datos.unidades.factorLONG = model.datos.unidades.factorLONG * 39.37007874015748
            model.datos.unidades.factorSUP = model.datos.unidades.factorSUP * 39.37007874015748 ^ 2
            model.datos.unidades.factorEG = model.datos.unidades.factorEG / 39.37007874015748 ^ 2
            model.datos.unidades.factorDEN = model.datos.unidades.factorDEN / 39.37007874015748 ^ 3
        Case "feet"
            model.datos.unidades.factorLONG = model.datos.unidades.factorLONG * 3.280839895013123
            model.datos.unidades.factorSUP = model.datos.unidades.factorSUP * 3.280839895013123 ^ 2
            model.datos.unidades.factorEG = model.datos.unidades.factorEG / 3.280839895013123 ^ 2
            model.datos.unidades.factorDEN = model.datos.unidades.factorDEN / 3.280839895013123 ^ 3
        Case Else
            model.datos.unidades.long_nombre = "metr"
    End Select

    Select Case LCase$(model.datos.unidades.ang_nombre)
        Case "rads"
            ' nada!!! porque es default
        Case "grad"
            model.datos.unidades.factorANG = model.datos.unidades.factorANG * 180 / 3.141567
        Case Else
            model.datos.unidades.ang_nombre = "rads"

    End Select

End Sub

' Public Sub logear(linea As String)
'
'     Try Print #flags.LogFile, Format$(Now, "hh:mm:ss") & "-" & linea
'     'fmain.pl.Text = fmain.pl.Text + linea + Chr$(13) + Chr$(10)
'
' End Sub

' Public Function openlog() As Boolean
'
'     Dim a As Integer
'
'     If flags.LogFileName = "" Then flags.LogFilename = "log.txt"
'     'On Error Goto err_log:
'     'If existe[flags.LogFile] Then Kill flags.LogFile
'
'     flags.LogFile = Open user.home &/  ".estru3d" &/ flags.LogFilename For Create
'
'     Return
'
' Catch
'     Message.Warning(("No puedo abrir el archivo log"))
'
'     Return False
'
' End Function

Public Sub closelog()

    Try Close #flags.LogFileNumber

End Sub

Public Sub DetectarMasas() 'As Integer

    Dim a As Integer, b As Integer, n As Integer

    b = 0
    For n = 1 To e3d.model.nudo.max
        sisMasas[n] = 0

        For a = 1 To e3d.model.barra.Count
            If (model.barra[a].ni = n) Or (model.barra[a].nf = n) Then
                sisMasas[n] += 0.5 * longitud(a) * model.barra[a].material.densidad * model.secciones[model.barra[a].seccion].area

            End If
        Next
    Next

End Sub

Public Sub BorrarEstado(e As Integer)
    ' borras todas las cargas de ese estado

    Dim a As Integer
    Dim bar As ClsBarra, nud As ClsNudo, p As Integer
    Dim carga As ClsCargaBarra

    For Each nud In model.nudo ' a = 1 To cargas model.nudo.max
        For a = nud.cargas.Max To 0 Step -1
            If nud.cargas[a].Estado = e Then nud.cargas.Remove(a) ' BorrarCargaNudo(a)
        Next

    Next

    'ListarCargasBarras(1)
    For Each bar In model.barra 'a = 1 To cargas model.barra.max
        For a = bar.cargas.Max To 0 Step -1
            If bar.cargas[a].e = e Then bar.cargas.Remove(a) '           BorrarCargaBarra(a)
        Next
    Next

End Sub

' Public Function get_material(cual As String) As Integer
'
'     Dim a As Integer
'
'     cual = LCase$(cual)
'     For a = 1 To 20
'         If InStr(LCase$(material[a].nombre), cual) > 0 Then
'             Return a
'
'         End If
'     Next
'
' End Function

Public Function AddNudo(x As Float, Y As Float, z As Float, Optional CheckExisting As Boolean, Tolerance As Float = 1e-5, Auxiliar As Boolean = False) As String
    ' devuelve el numero de model.nudo o cero en caso de error

    'Tolerance: to surpass numerical tricks comparing coordinates,
    'ie: x = 12.50 tests True against x0 = 12.50001 if tolerance = 0.005
    'then no new node is created

    Dim a As Integer
    Dim n As ClsNudo
    ' primero chequeo que no exista
    If CheckExisting Then

        For Each n In model.nudo
            If (Abs(n.x - x) <= Tolerance) And (Abs(n.Y - Y) <= tolerance) And (Abs(n.z - z) <= Tolerance) Then

                ' encontre un model.nudo con las mismas coordenadas, devuelvo su posicion
                If auxiliar = False Then n.Auxiliar = False
                Return n.handle

            End If
        Next
    End If

    ' ahora veo si el array tiene elementos extra disponibles

    Dim nudou As New ClsNudo 'nudotype4
    Dim LastIndex As Integer
    Try LastIndex = model.nudo[model.nudo.Last].indice
    nudou.handle = GetNewHandle()
    nudoU.x = x
    nudoU.Y = Y
    nudoU.z = z
    nudou.Indice = LastIndex + 1
    nudou.Auxiliar = auxiliar

    model.nudo.Add(nudou, nudou.handle)

    flags.cambios = True
    flags.calculado = False

    Return nudou.handle

End Function

'' Devuelve un handle disponible
Fast Public Function GetNewHandle() As String

    Dim s As String

    Do

        Inc model.LastHandle

        s = Hex(model.LastHandle)
        If Not model.partes.Exist(s) Then Break
    Loop
    Return s

End

Fast Public Function ReIndexNodes() As Boolean
    ' los indices de los model.nudos van de 1 a nNudos

    Dim i As Integer

    For Each n As ClsNudo In model.nudo
        Inc i
        n.indice = i

    Next
    i = 0
    For Each b As Clsbarra In model.barra
        Inc i
        b.indice = i

    Next

End

Public Function AddBarra(nudo_inicial As String, nudo_final As String, Optional sSeccion As ClsSeccion, sMaterial As ClsMaterial, rotulas As Integer = 0, CheckExisting As Boolean = False) As String
    ' 2025 la vamos a mejorar para ue acepte mas cosas
    ' devuelve el numero de model.barra o cero en caso de error
    ' rotulas:  0=sin rotulas, 1=rotula en model.nudo inicial, 2=en model.nudo final, 3=en ambos
    ' material y seccion: numero de orden o cero

    Dim d As Integer
    Dim b As ClsBarra
    ' primero chequeo que no exista
    If CheckExisting Then
        For Each b In model.barra 'd = 1 To  model.barra.Count
            If (b.nF = nudo_final) And (b.ni = nudo_inicial) Then
                Return b.handle

            End If
        Next
    End If

    ' agrego una barra
    flags.cambios = True
    flags.calculado = False

    Dim barrau As New ClsBarra

    barrau.ni = nudo_inicial  '2020 what if node doesnt exist?
    barrau.nF = nudo_final
    barrau.handle = GetNewHandle()

    If smaterial Then

        barrau.material = sMaterial
    Else

        barrau.material = GetMaterialByName("unitario")

    End If

    If sseccion Then
        barrau.seccion = sseccion
    Else
        barrau.seccion = GetSeccionByName("unitaria")

    End If

    barrau.grupo = 0
    barrau.restriccion = rotulas

    model.barra.Add(barrau, barrau.handle)

    Return barrau.handle

End Function

Public Sub Decir(loque As String)
    'fmain.texto.Caption = loque
    'fmain.texto.Enabled = False

End Sub

Public Sub PurgarBarras()
    ' corrige barras con:
    ' ni>nf
    ' .seccion = nada
    ' .material = nada

    Dim a As Integer, b As Integer, t As Integer

    For a = 1 To model.barra.Count
        ' ni>nf
        If model.barra[a].ni > model.barra[a].nF Then
            b = model.barra[a].ni
            model.barra[a].ni = model.barra[a].nF
            model.barra[a].nF = b
            t += 1

        End If

    Next
    fmain.debugInfo(("Barras corregidas ") & Str$(t), False)

End Sub

'' Elimina todos los model.nudos que no esten agarrados de alguna barra
Public Function PurgarNudos() As Integer

    Dim a As Integer, e As Integer, tengo As Boolean
    Dim t As Integer
    Dim n As ClsNudo
    Dim b As ClsBarra

    For Each n In model.nudo 'e = 1 To e3d.nud
        tengo = False
        For Each b In model.barra ' a = 1 To  model.barra.Count
            '3
            If b.ni = n.handle Then tengo = True
            If b.nF = n.handle Then tengo = True
            If tengo Then Break
        Next
        If Not tengo Then
            Inc t

            model.nudo.Remove(n.handle)
            'reacomodo las barras
            ' 2020 obsooleto
            ' For a = 1 To  model.barra.Count
            '     '3
            '     If barra[a].ni >= e Then barra[a].ni -= 1
            '     If barra[a].nF >= e Then barra[a].nF -= 1
            ' Next

        End If

    Next
    fmain.debugInfo(("Nudos sueltos purgados ") & Str$(t), False)

    Return t

End Function

Public Sub Asistir()
    ' aca vamops a sistir al user para q pueda disenie\
    ' para indicar el estado de la estructura
    ' TODO: hace una nueva version de esto estilo Console

    '
    '     Dim a As Integer, ok As Integer, ok2 As Integer, nF As String, nFo As String, er As String
    '     Dim ve As String, cmd As String, cmdl As String
    '     Dim t As Long
    ' paso1:
    '
    '     nF = Application.Path &/ "/hlp" &/ flags.lenguaje &/ "asis_1.htm"
    '
    '     nFo = User.Home &/ ".estru3d/asis_1.htm"
    '
    '     If Exist(nfo) Then
    '         Try Kill nfo
    '         If Error > 0 Then
    '             Message(("No puedo mostrar el asistente"))
    '             Return
    '         Endif
    '     Endif
    '     Copy nF To nFo
    '     'If model.datos.proyecto <> "" Then
    '     '    ok2 = utils.file_replace(nFo, "__archivo", model.datos.proyecto]
    '     'Else
    '     '    ok2 = utils.file_replace(nFo, "__archivo", "[no definido]"]
    '     'End If
    '     'If Left$[opcionales.descripcion, 1] = Chr$[0] Then
    '     '    ok2 = utils.file_replace(nFo, "__descripcion", "[no definido]"]
    '     'Else
    '     '    ok2 = utils.file_replace(nFo, "__descripcion", opcionales.descripcion]
    '     'End If
    '     ok2 = utils.file_replace(nFo, "__nudos", Str$(e3d. model.nudo.max))
    '     ok2 = utils.file_replace(nFo, "__barras", Str$( model.barra.Count))
    '
    '     ok2 = utils.file_replace(nFo, "__carbar", Str$(model.datos.totalcargasbarra))
    '     ok2 = utils.file_replace(nFo, "__cargas", Str$(model.datos.totalcargasnudo))
    '     ok2 = utils.file_replace(nFo, "__apoyos", Str$(e3d.apoyos.count))
    '     ok2 = utils.file_replace(nFo, "__secciones", Str$( model.secciones.count))
    '     ok2 = utils.file_replace(nFo, "__materiales", Str$(material_count()))
    '
    '     ok2 = utils.file_replace(nFo, "__cargas", Str$(t))
    '     SetGL
    '     Select Case model.datos.tipo
    '         Case 1
    '             ok2 = utils.file_replace(nFo, "__tipo", ("Reticulado plano"))
    '
    '         Case 3
    '             ok2 = utils.file_replace(nFo, "__tipo", ("Portico plano"))
    '
    '         Case 2
    '             ok2 = utils.file_replace(nFo, "__tipo", ("Reticulado espacial"))
    '
    '         Case 4
    '             ok2 = utils.file_replace(nFo, "__tipo", ("Portico espacial"))
    '
    '         Case Else
    '             ok2 = utils.file_replace(nFo, "__tipo", ("[no definido]"))
    '             ve = ("No esta definido el tipo de estructura, este es el primer paso que debe hacerse para empezar el modelado")
    '             cmd = "info.cmd"
    '             cmdl = ("Definir el tipo de estructura")
    '             Goto salida
    '     End Select
    '
    '     ok = chequeoestructura(check_nudos Or check_barras Or check_datos Or check_apoyos)
    '
    '     ' error_nudossueltos = 1, error_nudosduplicados = 2, error_nudosinsuficientes = 4
    '     ' error_barrasinsuficientes = 8, error_barrassueltas = 16, error_barrassindatos = 32
    '     ' error_apoyosinsuficientes = 32, error_rotulas = 64 ', error_barrassindatos = 32
    '     t = 0 ' problemas
    '     'verifico el numero de model.nudos
    '     ok = chequeoestructura(check_nudos)
    '     If (ok And error_nudosinsuficientes) = error_nudosinsuficientes Then
    '         ve = ("No hay model.nudos suficientes debe haber como minimo 2 model.nudos y una  model.barra.")
    '         cmd = "info.cmd"
    '         cmdl = ("Definir el numero de model.nudos")
    '         Goto salida
    '     End If
    '     'y el de barras
    '     ok = chequeoestructura(check_barras)
    '     'Stop
    '     If (ok And error_barrasinsuficientes) = error_barrasinsuficientes Then
    '         ve = ("No hay barras suficientes debe haber como minimo 2 model.nudos y una  model.barra.")
    '         cmd = "info.cmd"
    '         cmdl = ("Definir el numero de barras")
    '         Goto salida
    '     End If
    '
    '     ' definio los model.nudos?
    '     For a = 1 To e3d. model.nudo.max
    '         If (model.nudo[a].x = 0) And (model.nudo[a].Y = 0) And (model.nudo[a].z = 0) Then t = t + 1
    '     Next
    '     'Stop
    '
    '     If t > 1 Then
    '         ve = ("Hay model.nudos que no estan definidos todavia, en la tabla de model.nudos se indican las coordenadas x,y,z de cada  model.nudo.")
    '         cmd = "nudos.cmd"
    '         cmdl = ("Definir las coordenadas de los model.nudos")
    '         Goto salida
    '
    '     End If
    '
    '     ok = chequeoestructura(check_barras)
    '     If (ok And error_nimayor) = error_nimayor Then
    '         ve = ("Hay barras con el model.nudo inicial mayor que el final. Este programa usa como condicion que al")
    '         ve = ve & (" una model.barra el model.nudo inicial tenga un numero menor que el final.")
    '         cmd = "purgarbarras.cmd"
    '         cmdl = ("Corregir la numeracion de barras")
    '         Goto salida
    '
    '     End If
    '
    '     If (ok And error_barrassueltas) = error_barrassueltas Then
    '         ve = ("Barras no tienen los model.nudos definidos. Todas las barras deben tener model.nudo inicial y final.")
    '         cmd = "barras.cmd"
    '         cmdl = ("r la Tabla de Barras para completar los valores de model.nudo inicial y final")
    '         Goto salida
    '
    '     End If
    '
    '     ok = chequeoestructura(check_nudos)
    '     If (ok And error_nudossueltos) = error_nudossueltos Then
    '         ve = ("Hay model.nudos a los que no llegan barras.")
    '         cmd = "purgarnudos.cmd"
    '         cmdl = ("Haga click aqui para eliminar los model.nudos que estan sueltos")
    '         Goto salida
    '     Else If (ok And error_nudosduplicados) = error_nudosduplicados Then
    '         ve = ("Hay model.nudos en la misma posición.")
    '         cmd = "purgarnudos.cmd"
    '         cmdl = ("Haga click aqui para eliminar los model.nudos que estan en la misma posicion")
    '         Goto salida
    '     End If
    '
    '     ok = chequeoestructura(check_datos)
    '     If (ok And error_barrassindatos) = error_barrassindatos Then
    '         ve = ("Barras no tienen los datos definidos. Debe definirse la seccion de la model.barra y el material.")
    '         cmd = "barras.cmd"
    '         cmdl = ("Corregir la seccion y/o material de las barras")
    '         Goto salida
    '
    '     End If
    '     If (ok And error_rotulas) = error_rotulas Then
    '         ve = ("Hay rótulas que generan un mecanismo. Esto significa que a todas las barras que llegan a un model.nudo se las definio como rotula en dicho extremo.")
    '         cmd = "extremos.cmd"
    '         cmdl = ("Corregir los extremos de las barras")
    '         Goto salida
    '
    '     End If
    '
    '     t = 0
    '
    '     ' ahora verifico apoyos, o eso intento
    '     For a = 1 To e3d.apoyos.max
    '         If (apoyos[a].nudo <> 0) Then t = t + 1
    '     Next
    '     'Stop
    '
    '     If t = 0 Then
    '         ve = ("No se han colocado apoyos.")
    '         cmd = "apoyos.cmd"
    '         cmdl = ("Colocar apoyos")
    '         Goto salida
    '
    '     End If
    '
    '     'cargas
    '     t = 0
    '     For a = 0 To cargas model.nudo.max
    '         If (cargasnudo[a].nudo <> 0) Then t = t + 1
    '     Next
    '     For a = 0 To cargas model.barra.max
    '         If (cargasbarra[a].barra <> 0) Then t = t + 1
    '     Next
    '
    '     If t = 0 Then
    '         ve = ("No se han colocado cargas.")
    '         cmd = "cargas.cmd"
    '         cmdl = ("Colocar cargas")
    '         Goto salida
    '
    '     End If
    '
    '     If ok = 0 Then
    '         ve = ("No hay problemas que informar. Puede calcularse.")
    '         cmd = "calcular.cmd"
    '         cmdl = ("Cerrar el asistente y calcular")
    '         Goto salida
    '
    '     End If
    '
    ' salida:
    '
    '     'Stop
    '     ok2 = utils.file_replace(nFo, "__veredicto", ve)
    '     ok2 = utils.file_replace(nFo, "__paso", cmdl)
    '     ok2 = utils.file_replace(nFo, "__cmd", cmd)

End Sub

Public Sub WebAction(cmd As String)

    Dim a As Integer

    Select Case cmd
        Case "info"
            ' muestro la ventana info
            formInfo.Showmodal

            If flags.modo = 3 Then Asistir

        Case "purgarnudos"
            PurgarNudos
            If flags.modo = 3 Then Asistir

        Case "purgarbarras"
            PurgarBarras
            If flags.modo = 3 Then Asistir

        Case "nudos"
            FormNudos.Showmodal

            If flags.modo = 3 Then Asistir
        Case "barras"
            FormBarras.Showmodal
            If flags.modo = 3 Then Asistir
        Case "extremos"
            'extremos.Show 1

            If flags.modo = 3 Then Asistir

        Case "apoyos"
            formApoyos.ShowModal

            If flags.modo = 3 Then Asistir
        Case "cargas"
            formCargasNudos.ShowModal

            If flags.modo = 3 Then Asistir
        Case "calcular"
            '
            flags.modo = 1
            fmain.SetStatus
            '    Stop
            clc.IniciarCalculos

    End Select

End Sub

Public Sub SetGL()

    Select Case model.datos.tipo
        Case 0, porticoplano
            clc.gr = 3
            model.datos.tipo = porticoplano

        Case reticuladoplano
            clc.gr = 2
        Case porticoplano, reticuladoespacial
            clc.gr = 3
        Case porticoespacial
            clc.gr = 6
    End Select

End Sub

Public Sub main()

    'tareas en caso de que sea la primera vez que se corra el programa, o su actualizacion

    Debug Application.Args[0]
    Debug Application.Args[1]
    Debug Application.Args[2]
    Debug Application.Args[3]

    FirstRun

    ' todo en orden

    Inicializar

    fmain.Show

End

Public Function EscribeUnidadesDeMedida() As String
    'tiene que ser un textlabel para que admita etiquetas html

    Dim texto As String

    Texto = "<center>" & "<i>" & ("Unidades de Medidas:") & " </i>" & "<br>" & " <b>" & ("Longitud:") & "</b> " & model.datos.unidades.long_nombre
    texto &= " <b>" & ("Peso:") & "</b> " & model.datos.unidades.peso_nombre
    texto &= " <b>" & ("Angulo:") & "</b> " & model.datos.unidades.ang_nombre
    texto &= "</center>"

    Return texto

End

Public Sub Inicializar()
    'variables

    Dim a As Integer, p1 As New Punto3d, p2 As New Punto3d, px As New Punto3d
    Dim LibPath As String, LibVersion As Float
    'forzamos a utilizar ingles, esto sirve para usuarios de otro idioma que no tienen spanish instalado
    If Application.Args[1] = "-en" Then System.Language = "en_US.UTF-8"

    Tutoriales = New Settings(Application.Path &/ "/hlp" &/ flags.lenguaje &/ "tutorial.estru3d-lib", "Tutoriales")

    'Debug Application.Dir

    'Debug Application.Name

    extremos[0] = "+---+"  'empotrada
    extremos[1] = "o---+"  'empotrada-rotula
    extremos[2] = "+---o"
    extremos[3] = "o---o"
    extremos[4] = "<--->"  'tensor

    model = New Model
    PonerEnCero()
    model.graficos.colores.barras = 180
    model.graficos.colores.seleccion = 60

    flags.OcultarCargas = True
    flags.MostrarDespuesCalculo = 1 ' Mz
    'Cargo los settings

    setting.formato_datos = parametros["Options/DataFormat", "0.00"]
    setting.formato = parametros["Options/ResultsFormat", "0.00"]
    e3d.flags.ayuda = Application.Path &/ "/hlp" &/ flags.lenguaje &/ "bienv.htm"
    e3d.flags.ayuda = Application.Path &/ "/hlp" &/ e3d.flags.lenguaje &/ "index.htm"
    e3d.setting.IntervaloElastica = 20
    setting.solver = parametros["Options/Solver", "4"]

    FontList = glx.LoadFonts(config.dirResources &/ "Librerias/fonts/lff")
    'FontList = glx.LoadFonts(gcd.sFonts)
    glx.SelectFont("romans")

    Return

End

Public Sub NuevoProyecto()

    PonerEnCero

    fmain.SetStatus

End Sub

Public Sub aEsfSec(hbarra As Integer, secc As Integer, esfuerzo As Integer, valor As Float)

    ' coloca el valor en la seccion
    ' como todo es 1 to xxxx, resto 1 a todo
    Dim pos As Long
    ' esfsecarray.resize ( barras * setting.pasoc * 6)
    ' 10 barras, 20 model.secciones + 1 , 6 espacial -> 10 * 21 * 6 = 1260 elementos
    '
    pos = (esfuerzo - 1) + secc * 6 + (hbarra - 1) * (setting.PasoCalcularEsfuerzos + 1) * 6

    model.esfsecarray[pos] = valor

End

Public Function EsfSec(hbarra As Integer, secc As Integer, esfuerzo As Integer) As Float

    ' devuelve el valor en la seccion
    ' como todo es 1 to xxxx, resto 1 a todo
    Dim pos As Long

    pos = (esfuerzo - 1) + secc * 6 + (hbarra - 1) * (setting.PasoCalcularEsfuerzos + 1) * 6

    Return model.esfsecarray[pos]

End

Public Function EsfSecNeg(hbarra As Integer, secc As Integer, esfuerzo As Integer) As Float

    ' devuelve el valor en la seccion
    ' como todo es 1 to xxxx, resto 1 a todo
    Dim pos As Long

    pos = (esfuerzo - 1) + secc * 6 + (hbarra - 1) * (setting.PasoCalcularEsfuerzos + 1) * 6

    Return model.esfsecarrayNeg[pos]

End

Public Function EsfSecPos(hbarra As Integer, secc As Integer, esfuerzo As Integer) As Float

    ' devuelve el valor en la seccion
    ' como todo es 1 to xxxx, resto 1 a todo
    Dim pos As Long

    pos = (esfuerzo - 1) + secc * 6 + (hbarra - 1) * (setting.PasoCalcularEsfuerzos + 1) * 6

    Return model.esfsecarrayPos[pos]

End

' idem(model.losas
Public Sub aEsfSecLosas(hLosa As ClsLosa, x As Integer, Z As Integer, direccion As Integer, esfuerzo As Integer, valor As Float)

    ' coloca el valor en la cuadricula de las(model.losas
    ' las(model.losas son de nX x nY cuadrados
    ' por lo tanto el array sera de: A = 6 esfuerzos x (nX + 1) x (nY + 1)
    ' cuando creo el array acumulador, sera de la sumatoria de A(l)
    '
    Dim pos As Long
    ' El indice en el array acumulador se obtiene por
    pos = hLosa.EsfSecArrayLosasIndex 'model.EsfSecArrayLosasIndex[hLosa]

    ' y la posicion adecuada, considereando que acumulamos por filas X
    pos += (direccion - 1) + (esfuerzo - 1) * 2 + Z * (hlosa.nxGrid + 1) * 6 * 2 + X * 6 * 2

    model.EsfSecArrayLosas[pos] = valor

End

Public Function EsfSecLosas(hLosa As ClsLosa, x As Integer, Z As Integer, direccion As Integer, esfuerzo As Integer) As Float

    ' devuelve el valor en la cuadricula
    Dim pos As Long
    ' El indice en el array acumulador se obtiene por
    pos = hLosa.EsfSecArrayLosasIndex 'model.EsfSecArrayLosasIndex[hLosa]

    ' y la posicion adecuada, considereando que acumulamos por filas X
    pos += (direccion - 1) + (esfuerzo - 1) * 2 + Z * (hlosa.nxGrid + 1) * 6 * 2 + X * 6 * 2

    Return model.EsfSecArrayLosas[pos]

End

Public Sub LlenarGridLosas()

    ' llena el array de esfuerzos en las(model.losas
    Dim l As Clslosa
    Dim pos As Integer
    Dim pX As Integer ' posicion X
    Dim pZ As Integer ' posicion Z
    Dim d As Integer ' la direccion del esfuerzo a considerar
    Dim b As Integer ' barras
    Dim E As Float ' el esfuerzo
    Dim E2 As Float
    Dim esfuerzo As Integer
    Dim nudoI, nudoF As String

    Dim s As String

    For Each l In model.losas
        l.GridLosasIndex = pos
        pos += 3 * (l.nxGrid + 1) * (l.nzGrid + 1)
    Next

    model.arrGridlosas.Resize(pos) '(model.GridLosasIndex[l] + 3 * (model.losas[l].nxGrid + 1) * (model.losas[l].nzGrid + 1))

    ' ahora empiezo a acumular
    For Each bar As ClsBarra In model.barra
        If bar.tipo = tipo_losa Then ' es parte de una losa?
            l = model.losas[bar.grupo] ' numero de losa
            pX = bar.PosX  ' en general las posiciones 0 y ultimas quedan reemplaadas por model.vigas
            pZ = bar.PosZ
            d = bar.Eje '1=X 2=Z
            nudoI = bar.ni
            nudoF = bar.Nf

            If bar.Invertida Then Swap nudoI, nudoF

            'veo que pasa con la posicion
            If (d = 1) And (pX = 1) Then
                '  ademas cargo el punto
                aGridLosas(l, 0, pZ, model.nudo[NudoI].x, model.nudo[Nudoi].y, model.nudo[Nudoi].z)
            Else If (d = 2) And (pZ = 1) Then ' tomo el esfuerzo en el inicio

                '  ademas cargo el punto
                aGridLosas(l, pX, 0, model.nudo[NudoI].x, model.nudo[NudoI].y, model.nudo[NudoI].z)
            End If

            aGridLosas(l, pX, pz, model.nudo[NudoF].x, model.nudo[NudoF].y, model.nudo[NudoF].z)

        End If
    Next

    For Each l In model.losas
        ' acumulo los limites de las(model.losas
        aGridLosas(l, 0, 0, model.nudo[l.Nudo1].x, model.nudo[l.Nudo1].y, model.nudo[l.Nudo1].z)
        aGridLosas(l, 0, l.nzgrid, model.nudo[l.Nudo3].x, model.nudo[l.Nudo3].y, model.nudo[l.Nudo3].z)
        aGridLosas(l, l.nxgrid, 0, model.nudo[l.Nudo2].x, model.nudo[l.Nudo2].y, model.nudo[l.Nudo2].z)
        aGridLosas(l, l.nxGrid, l.nzgrid, model.nudo[l.Nudo4].x, model.nudo[l.Nudo4].y, model.nudo[l.Nudo4].z)

    Next

End

' idem(model.losas
Public Sub aGridLosas(hLosa As ClsLosa, X As Integer, Z As Integer, x0 As Float, y0 As Float, z0 As Float)

    ' coloca el valor en la cuadricula de las(model.losas
    ' las(model.losas son de nX x nY cuadrados
    ' por lo tanto el array sera de: A = 6 esfuerzos x (nX + 1) x (nY + 1)
    ' cuando creo el array acumulador, sera de la sumatoria de A(l)
    '
    Dim pos As Long
    ' El indice en el array acumulador se obtiene por
    pos = hlosa.GridLosasIndex 'model.GridLosasIndex[hLosa]

    ' y la posicion adecuada, considereando que acumulamos por filas X
    pos += Z * (hlosa.nxGrid + 1) * 3 + X * 3

    model.arrGridLosas[pos] = x0
    model.arrGridLosas[pos + 1] = y0
    model.arrGridLosas[pos + 2] = z0

End

' Public Sub GridLosas(hLosa As Integer, x As Integer, Z As Integer, ByRef X0 As Float, ByRef y0 As Float, ByRef z0 As Float)
'
'     ' devuelve el valor en la cuadricula
'     Dim pos As Long
'
'     pos = model.GridLosasIndex[hLosa]
'
'     ' y la posicion adecuada, considereando que acumulamos por filas X
'     pos += Z * (model.losas[hLosa].nxGrid + 1) * 3 + X * 3
'
'     x0 = model.arrGridLosas[pos]
'     y0 = model.arrGridLosas[pos + 1]
'     z0 = model.arrGridLosas[pos + 2]
'
' End

Public Sub GridLosas3D(hLosa As ClsLosa, x As Integer, Z As Integer, P3d As Punto3d)
    ' 2020
    ' TODO chequear qe P3D se pase ByRef
    ' devuelve el valor en la cuadricula

    Dim pos As Long

    pos = hlosa.GridLosasIndex

    ' y la posicion adecuada, considereando que acumulamos por filas X
    pos += Z * (hlosa.nxGrid + 1) * 3 + X * 3

    p3d.x = model.arrGridLosas[pos]
    p3d.y = model.arrGridLosas[pos + 1]
    p3d.z = model.arrGridLosas[pos + 2]

End

Public Function FirstRun()

    Dim archivo As String
    '
    ' copio la libreria C para poder usarla
    e3d.flags.lenguaje = Left$(System.Language, 2)  ' con esto accedo al folder correcto de la ayuda

    '2020
    'en alggunos ambientes como WLS esto puede dar un valor erroneo

    If InStr("en es ", e3d.flags.lenguaje) = 0 Then e3d.flags.lenguaje = "es"

    ' es la primera vez que corro el programa?
    If parametros["User/LocalVersion", ""] <> Application.Version Then ' a new version is beign installed

        ' user debe aceptar los terminos
        'If parametros["User/Agreed", "False"] <> "True" Then
        FormAgreement.ShowModal
        If parametros["User/Agreed", "False"] <> "True" Then Quit
        'End If
        parametros["User/LocalVersion"] = Application.Version
        If Not Exist(User.home &/ ".estru3d/") Then Mkdir User.home &/ ".estru3d"
        If Not Exist(User.home &/ ".estru3d/Librerias/") Then Mkdir User.home &/ ".estru3d/Librerias"

        If parametros["User/FirstRun", "True"] = "True" Then

            For Each archivo In RDir(Application.Path &/ "Librerias/")
                Try Kill User.home &/ ".estru3d/Librerias/" &/ archivo
                Copy Application.Path &/ "Librerias/" &/ archivo To User.home &/ ".estru3d/Librerias/" &/ archivo
            Next
            parametros["User/FirstRun"] = "False"
        Else If Message(("Reemplazamos las tablas de materiales?")) Then

            For Each archivo In RDir(Application.Path &/ "Librerias/")
                Try Kill User.home &/ ".estru3d/Librerias/" &/ archivo
                Copy Application.Path &/ "Librerias/" &/ archivo To User.home &/ ".estru3d/Librerias/" &/ archivo
            Next

        Else

            ' se mantienen las tablas

        End If

    Endif

End

Public Sub JoinBars(bar As Integer)
    ' esta rutina busca barras colineales con la model.barra bar y las no

End

Public Sub GenerarSobrecargas(estado As Integer)
    ' genera cargas gravitatorias basandose en el material y la seccion, y las coloca en el estado indicado

    Dim b As ClsBarra 'Integer ' la model.barra a cargar
    Dim p As Float 'el peso por ml
    Dim c As ClsCargaBarra ' Integer ' carga
    Dim l As ClsLosa
    Dim n As Integer

    BorrarEstado(flags.estadoAccidental)
    BorrarEstado(flags.estadoPermanente)

    For Each l In model.losas
        Inc n
        fmain.debugInfo(("Generando sobrecargas ") & Format$(n / model.losas.max, "0.00%"), True)

        For Each b In model.barra ' = 1 To  model.barra.Count

            If b.tipo = tipo_losa And b.grupo = l.Handle Then ' estoy en la losa adecuada

                ' la superficie de influencia es Lbarra * 0.5, porque la cuadricula es cuadrada
                ' permanente
                p = l.g * longitud(b) * 0.5

                c = New ClsCargaBarra ' GetFreeCarga(flags.estadoPermanente)

                If IsNull(c) Then

                    fmain.debugInfo("No hay mas lugar para cargas.")
                    Return

                Endif

                b.cargas.Add(c)
                ' la linea siguiente es obsoleta
                ' cargasbarra[c].barra = b
                c.e = flags.estadoPermanente
                c.tipo = 22
                c.py = -p

                ' aaccidental
                p = l.p * longitud(b) * 0.5

                c = New ClsCargaBarra ' GetFreeCarga(flags.estadoAccidental)

                If IsNull(c) Then

                    fmain.debugInfo("No hay mas lugar para cargas.")
                    Return

                Endif
                b.cargas.Add(c)
                'cargasbarra[c].barra = b
                c.e = flags.estadoAccidental
                c.tipo = 22
                c.py = -p
            End If
        Next 'barras
    Next '(model.losas

End

Public Sub GenerarPesoPropio(estado As Integer)
    ' genera cargas gravitatorias basandose en el material y la seccion, y las coloca en el estado indicado

    Dim p As Float 'el peso por ml
    Dim b As ClsBarra 'Integer ' la model.barra a cargar

    Dim c As ClsCargaBarra ' Integer ' carga
    Dim l As ClsLosa

    ' fmain.debugInfo("Borre el estado?",, True)
    '
    ' e3d.ListarCargasBarras(, 1138)

    BorrarEstado(estado)

    ' fmain.debugInfo("Borre el estado?",, True)
    '
    ' e3d.ListarCargasBarras(, 1138)
    For Each b In model.barra ' = 1 To  model.barra.Count

        p = b.seccion.area * b.material.densidad

        If (b.tipo = tipo_losa) Then
            l = model.losas[b.grupo]
            p *= l.alivianado

        End If

        c = New ClsCargaBarra ' GetFreeCarga(estado)

        If IsNull(c) Then

            fmain.debugInfo("No hay mas lugar para cargas.")
            Return

        Endif
        b.cargas.Add(c)
        ' cargasbarra[c].barra = b
        c.e = estado
        c.tipo = 22
        c.py = -p

    Next

End

Public Function addViga(ni As String, nf As String, seccion As ClsSeccion, Optional material As ClsMaterial, b As Integer = 0, d As Integer = 0) As ClsViga

    Dim viga1 As New ClsViga
    Dim bar1 As Integer

    viga1.Handle = GetNewHandle()
    viga1.nudo1 = ni
    viga1.nudo2 = nf
    viga1.seccion = seccion
    viga1.b = b
    viga1.d = d
    viga1.material = material

    model.vigas.Add(viga1, viga1.Handle)

    ' bar1 = AddBarra(ni, nf, seccion, material, 0, False)
    ' model.barra[bar1].grupo = model.vigas.Max
    ' model.barra[bar1].tipo = e3d.tipo_viga
    ' model.barra[bar1].sector = piso ' primer planta tipo

    Return viga1

End

' Public Function addViga(ni As Integer, nf As Integer, seccion As ClsSeccion, Optional material As ClsMaterial, b As Integer = 0, d As Integer = 0) As Integer
'
'     Dim viga1 As New ClsViga
'     Dim bar1 As Integer
'
'     viga1.nudo1 = ni
'     viga1.nudo2 = nf
'     viga1.seccion = seccion
'     viga1.b = b
'     viga1.d = d
'     viga1.material = material
'
'     model.vigas.Add(viga1)
'
'     ' bar1 = AddBarra(ni, nf, seccion, material, 0, False)
'     ' model.barra[bar1].grupo = model.vigas.Max
'     ' model.barra[bar1].tipo = e3d.tipo_viga
'     ' model.barra[bar1].sector = piso ' primer planta tipo
'
'     Return model.vigas.Max
'
' End

Public Function addColumna(ni As String, nf As String, seccion As ClsSeccion, Optional material As ClsMaterial, Ax As Integer = 0, Az As Integer = 0) As ClsColumna

    Dim c1 As New ClsColumna
    Dim bar1 As Integer

    c1.Handle = GetNewHandle()
    c1.nudo1 = ni
    c1.nudo2 = nf
    c1.seccion = seccion
    c1.ax = ax
    c1.az = az
    c1.material = material

    model.columna.Add(c1, c1.Handle)

    ' bar1 = AddBarra(ni, nf, seccion, material, 0, False)
    ' model.barra[bar1].grupo = model.vigas.Max
    ' model.barra[bar1].tipo = e3d.tipo_viga
    ' model.barra[bar1].sector = piso ' primer planta tipo

    Return c1

End

Public Sub ToDo()
    ' Solo un contenedor de las cosas que quiero implementar

    ' Preview: podria aprovechar la ultima vez que el user haga un zoom extents, o cuando cierra o guarda el proyecto
    '           para generar una imagen .png o .jpg que pueda utilizar luego a modo de preview

    'Envolventes: limpiar arrays cuando hubo modificaciones y haya que recalcular

End

Public Function ProcesarComando(cmd As String) As String
    ' supongo un comando estilo:
    ' filter piso1
    ' select beam from piso1

    ' en todo caso el comando empieza por una palabra
    Dim cmdl As String, a As Integer, b As Integer, params As String[], contador As Integer

    cmdl = LCase$(cmd)
    params = Split(cmdl, " ")
    If params.Count = 0 Then Return
    contador = 0
    Select Case Trim$(params[0])
        Case "select", "sel"
            ' se van a visualizar solo los elementos que cumplan el criterio
            Select Case Trim$(params[1])
                Case "all"
                    For a = 1 To model.barra.Max
                        model.barra[a].seleccionado = True
                        contador += 1
                    Next
                Case "beams"
                    For a = 1 To model.barra.Max
                        If model.barra[a].tipo = tipo_viga Then
                            model.barra[a].seleccionado = True
                            contador += 1
                        End If
                    Next
                Case "nothing"
                    For a = 1 To model.barra.Max
                        model.barra[a].seleccionado = False
                    Next

            End Select

            grf.valoresdelgrafico3D  'para que recalcule las escalas
            grf.dibujar_estructura3D 'ahora dibujamos
            Return ("Seleccionadas: ") & Str$(contador) & (" barras.")

        Case Else
            Return ("Error: Comando desconocido.")
    End Select

End

Public Function ErrorString(codigo As Integer) As String

    Dim er As String

    If (codigo And error_nudossueltos) = error_nudossueltos Then er = er & ("- model.nudos a los que no llegan barras.") & Chr$(13) & Chr$(10)
    If (codigo And error_nudosduplicados) = error_nudosduplicados Then er = er & ("- Hay model.nudos en la misma posición.") & Chr$(13) & Chr$(10)
    If (codigo And error_nudosinsuficientes) = error_nudosinsuficientes Then er = er & ("- No hay model.nudos suficientes.") & Chr$(13) & Chr$(10)
    If (codigo And error_barrasinsuficientes) = error_barrasinsuficientes Then er = er & ("- Barras insuficientes.") & Chr$(13) & Chr$(10)
    If (codigo And error_barrassueltas) = error_barrassueltas Then er = er & ("- Barras no tienen los model.nudos definidos.") & Chr$(13) & Chr$(10)
    If (codigo And error_barrassindatos) = error_barrassindatos Then er = er & ("- Barras no tienen los datos definidos.") & Chr$(13) & Chr$(10)
    If (codigo And error_nimayor) = error_nimayor Then er = er & ("- Barras con model.nudo inicial mayor que el final.") & Chr$(13) & Chr$(10)
    If (codigo And error_rotulas) = error_rotulas Then er = er & ("- Hay rótulas que generan un mecanismo.") & Chr$(13) & Chr$(10)

    If codigo = 0 Then er = ("Sin errores")

    Return er

End

Public Function GetElementTotalLength(hElement As String) As Float

    Dim b As ClsBarra
    Dim l As Float

    For Each b In model.barra
        If b.grupo = helement Then
            l += longitud(b)

        Endif
    Next
    Return l

End

Public Sub ReLoadLosa(l As ClsLosa, carga As Float, state As Integer)

    ' busca las barras que componen el elemento y elimina las cargas que tenga para el estado en cuestion

    ' recarga los elementos con la carga especificada
    ' carga = kg/m2 o sea que tengo que distribuirlos en las barras
    ' En caso de(model.losas la carga a aplicar en las barras seria repartida
    ' q = carga x sup / lTotal  , donde lTotal es la sumatoria de longitud de todas las barras que representan la losa

    Dim b As ClsBarra, ElSector As Integer
    Dim lTotal As Float, fCarga As Float
    Dim c As ClsCargaBarra, grupo As Integer, i, index As Integer

    ElSector = l.sector

    lTotal = GetElementTotalLength(l.Handle) ' Warning: las barras [].grupo = index de(model.losas/vigas + 1

    If lTotal = 0 Then
        fmain.debugInfo(("Elemento de largo 0"))
        Return
    Endif

    fCarga = carga * l.area / lTotal

    fmain.debugInfo(("Recargando losa ") & Str$(l.numero) & "-" & Str$(l.sector) & ":")
    fmain.debugInfo(("  Area ") & Format$(l.area, "0.00"),, True)
    fmain.debugInfo(("  Largo barras ") & Format$(lTotal, "0.00"),, True)
    fmain.debugInfo(("  Carga ") & Format$(fCarga, "0.00"),, True)

    ' primero elimino todas las cargas repartidas de esa losa del tipo gravitatorias
    For Each b In model.barra
        For i = 0 To b.cargas.Max  ' voy a borrar todas las cargas de esa model.barra para ese estado
            If i > b.cargas.max Then Break
            If (b.grupo = l.Handle) And (b.cargas[i].tipo = 22) And (b.cargas[i].e = state) Then b.cargas.Remove(i)
        Next
    Next

    For Each b In model.barra
        If (b.grupo = l.Handle) Then
            c = New ClsCargaBarra
            'c = GetFreeCarga(state)
            b.cargas.Add(c)
            c.py = -fCarga
            c.tipo = 22
            c.e = state

        Endif
    Next

End

Public Sub ReLoadViga(v As ClsViga, carga As Float, state As Integer)

    ' busca las barras que componen el elemento y elimina las cargas que tenga para el estado en cuestion

    ' recarga los elementos con la carga especificada
    ' carga = kg/m2 o sea que tengo que distribuirlos en las barras
    ' En caso de(model.losas la carga a aplicar en las barras seria repartida
    ' q = carga x sup / lTotal  , donde lTotal es la sumatoria de longitud de todas las barras que representan la losa

    Dim b As ClsBarra, ElSector As Integer
    Dim l As Float, lTotal As Float, fCarga As Float
    Dim c As ClsCargaBarra, grupo As Integer, i, index As Integer

    index = v.Handle

    ' primero elimino todas las cargas repartidas de esa losa del tipo gravitatorias
    For Each b In model.barra
        For i = 0 To b.cargas.Max  ' voy a borrar todas las cargas de esa model.barra para ese estado

            If (b.grupo = index) And (b.cargas[i].tipo = 22) And (b.cargas[i].e = state) Then
                ' If (index = 1) And (ElSector = 2) Then Stop

                b.cargas.Remove(i) ' BorrarCargaBarra(c)
            End If
        Next

    Next

    For Each b In model.barra '= 1 To  model.barra.Max
        If (b.grupo = index) And (Carga <> 0) Then
            ' If index = 1 And ElSector = 2 Then Stop

            c = New ClsCargaBarra ' GetFreeCarga(state)
            b.cargas.Add(c) 'cargasbarra[c].barra = b
            c.py = -Carga
            c.tipo = 22
            c.e = state

        Endif
    Next

End

Public Sub RecalcularAreaLosas()

    Dim a As Integer

    fmain.debugInfo(("Recalculando area de(model.losas"))

    ' TODO sirve para algo esto?? tal vez no

    For a = 0 To model.losas.max
        model.losas[a].area = modAlgebra.AreaRomboide3D(model.nudo[model.losas[a].Nudo1].xyz, model.nudo[model.losas[a].Nudo2].xyz, model.nudo[model.losas[a].Nudo4].xyz, model.nudo[model.losas[a].Nudo3].xyz)
        fmain.debugInfo(("Losa") & Str$(model.losas[a].piso) & "-" & Str$(model.losas[a].numero) & " " & Format$(model.losas[a].area, "0.00"))

    Next

End

' Public Function indexLosa(numero As Integer) As Integer
'
'     Dim a As Integer
'
'     For a = 0 To model.losas.Max
'         If model.losas[a].numero = numero Then Return a
'     Next
'     Return -1
'
' End

Public Function GetMaxGrid() As Integer

    Dim L As ClsLosa, c As Integer

    For Each L In model.losas
        If l.nxGrid > c Then c = l.nxGrid
        If l.nzGrid > c Then c = l.nzGrid
    Next

    setting.PasoGrid = c
    setting.PuntosInterpolados = 2

    Return c

End

Public Sub ListarCargasBarras(Optional iEstado As Integer = -1, iBarra As String = "")

    Dim a As Integer
    Dim b As ClsBarra, c As ClsCargaBarra
    ' lista las cargas para ese estado por consola
    For Each b In model.barra 'a = 0 To cargas model.barra.Max
        For Each c In b.cargas
            ' filtro
            If (c.e = iestado) Or (iEstado < 0) Then
                If (ibarra = "") Or (ibarra = b.handle) Then
                    fmain.debugInfo(" Carga en barra: " & Str(b.handle) & " Estado: " & Str(c.e) & " Tipo: " & Str(c.tipo) &
                        " P: " & Format$(c.px, "0.00") & Format$(c.py, "0.00") & Format$(c.pz, "0.00"))
                Endif
            End If
        Next
    Next

End

Public Sub ListarCargasNudos(estado As Integer)

    Dim a As Integer
    Dim n As ClsNudo
    Dim c As ClsCargaNudo
    ' lista las cargas para ese estado por consola
    For Each n In model.nudo 'a = 0 To cargas model.nudo.Max
        For Each c In n.cargas
            If c.Estado = estado Then
                fmain.debugInfo(" Carga en model.nudos " & Str(n.handle) & " P: " &
                    Format$(c.px, "0.00") & Format$(c.py, "0.00") & Format$(c.pz, "0.00") &
                    " M: " & Format$(c.mx, "0.00") & Format$(c.my, "0.00") & Format$(c.mz, "0.00"))
            Endif
        Next
    Next

End

Public Function FiltroBarra(iBarra As ClsBarra, Optional iSector As Integer = -1, iGrupo As String = "", iTipo As Integer = -1) As Boolean

    If iSector >= 0 Then
        If igrupo <> "" Then
            If ibarra.tipo = e3d.tipo_losa Then
                If model.losas.Exist(ibarra.grupo) Then Return True
            Else If ibarra.tipo = e3d.tipo_viga Then
                If model.vigas.Exist(ibarra.grupo) Then Return True
            Else If ibarra.tipo = e3d.tipo_columna Then
                If model.columna.Exist(ibarra.grupo) Then Return True
            Else If ibarra.tipo = e3d.tipo_tabique Then
                If model.tabiques.Exist(ibarra.grupo) Then Return True
            End If
        End If
    End If

    If (ibarra.tipo <> iTipo) And (iTipo >= 0) Then Return False

    Return True

End

Public Function GetMaterialByHandle(h As String) As ClsMaterial
    ' busca si tengo una seccion rectangular de esas caracteristicas, sino la crea y devuelve el indice

    Dim m As ClsMaterial

    For Each m In material

        If m.handle = h Then Return m

    Next

    Return material[material.First]

End

Public Function GetMaterialByName(name As String) As ClsMaterial
    ' busca si tengo una seccion rectangular de esas caracteristicas, sino la crea y devuelve el indice

    Dim m As ClsMaterial

    For Each m In material

        If m.nombre = name Then Return m

    Next

    Return material[material.First]

End

Public Function GetSeccionByName(name As String) As ClsSeccion
    ' busca si tengo una seccion rectangular de esas caracteristicas, sino la crea y devuelve el indice

    Dim seccu As New ClsSeccion

    For Each seccu In model.secciones

        If seccu.nombre = name Then Return seccu

    Next

    Return model.secciones[model.secciones.First]

End

Public Function GetSeccion(a As Float, b As Float) As ClsSeccion
    ' busca si tengo una seccion rectangular de esas caracteristicas, sino la crea y devuelve el indice

    Dim seccu As ClsSeccion

    For Each seccu In model.secciones

        If (seccu.a = a) And (seccu.b = b) And (seccu.tipo = "G-Rectangular") Then
            'tengo una seccion
            Return seccu

        End If
    Next

    seccu = New ClsSeccion

    seccU.a = a
    seccU.b = b
    seccU.tipo = "G-Rectangular"
    seccU.area = a * b
    seccU.iz = a * b ^ 3 / 12
    seccU.iy = a ^ 3 * b / 12
    seccU.ip = a ^ 3 * b / 12 + a * b ^ 3 / 12
    seccU.wy = a ^ 2 * b / 8
    seccU.wz = a * b ^ 2 / 8
    seccU.nombre = "R" & Format$(a, "0.00") & "x" & Format$(b, "0.00")
    seccu.handle = GetNewHandle()
    model.secciones.Add(seccU, seccU.nombre)

    Return seccu

End

Public Function FiltrarBarras(YaSelecionada As Boolean, Optional tipo As Integer = -1, Optional grupo As Integer = -1, Optional sector As Integer = -1, Optional material As String = "", Optional seccion As String = "") As Integer
    ' pone .seleccionado = True en todas las barras que cumplas las condiciones de los parametros
    '
    'Devuelve el total de barras seleccionadas

    Dim a As Integer, n As Integer

    For Each bar As Clsbarra In model.barra
        If bar.seleccionado Or Not YaSelecionada Then
            bar.seleccionado = True
            If tipo >= 0 And (bar.tipo <> tipo) Then bar.seleccionado = False ' no cumple
            If grupo >= 0 And (bar.grupo <> grupo) Then bar.seleccionado = False ' no cumple
            If material <> "" And (bar.material.nombre <> material) Then bar.seleccionado = False ' no cumple
            If seccion <> "" And (bar.seccion.nombre <> seccion) Then bar.seleccionado = False ' no cumple
            If sector >= 0 And (bar.sector <> sector) Then bar.seleccionado = False ' no cumple

            ' si sigue seleccionada, sumo

            If bar.seleccionado Then n += 1

        Endif
    Next
    Return n

End

Public Sub Esfuerzos_de_Barras_a_Vigas(Modo As Integer)

    'coloco en model.vigas[] los esfuerzos del ultimo calculo, segun Modo
    'Modo=0 -> reemplazo los valores
    'Modo=1 -> comparo y reemplazo la peor condicion
    'Modo=2 -> Sumo los valores
    'Modo=4 -> Sumo solo si empeora la condicion

    Dim b As Clsbarra
    Dim v As ClsViga
    Dim p As Integer
    Dim Inve As Float

    If Not flags.calculado Then
        fmain.debugInfo("No se ha calculado el proyecto aun")
        Return
    Endif

    For Each b In model.barra ' = 1 To  model.barra.Max
        ' busco determino si pertenece a alguna viga
        If b.tipo = tipo_viga Then
            v = GetPosViga(b.grupo)
            inve = 1 'IIf(model.barra[v].Invertida, -1, 1)
            ' comienzo a cargar los esfuerzos
            If modo = 0 Then
                If v.maxN < b.EsfExtBar.maxN * inve Then v.maxN = b.EsfExtBar.maxN * inve
                If v.maxQy < b.EsfExtBar.maxQy * inve Then v.maxQy = b.EsfExtBar.maxQy * inve
                If v.maxQz < b.EsfExtBar.maxQz * inve Then v.maxQz = b.EsfExtBar.maxQz * inve
                If v.maxT < b.EsfExtBar.maxT * inve Then v.maxT = b.EsfExtBar.maxT * inve
                If v.maxMy < b.EsfExtBar.maxMy Then v.maxMy = b.EsfExtBar.maxMy
                If v.maxMz < b.EsfExtBar.maxMz Then v.maxMz = b.EsfExtBar.maxMz

                If v.minN > b.EsfExtBar.minN * inve Then v.minN = b.EsfExtBar.minN * inve
                If v.minQy > b.EsfExtBar.minQy * inve Then v.minQy = b.EsfExtBar.minQy * inve
                If v.minQz > b.EsfExtBar.minQz * inve Then v.minQz = b.EsfExtBar.minQz * inve
                If v.minT > b.EsfExtBar.minT * inve Then v.minT = b.EsfExtBar.minT * inve
                If v.minMy > b.EsfExtBar.minMy Then v.minMy = b.EsfExtBar.minMy
                If v.minMz > b.EsfExtBar.minMz Then v.minMz = b.EsfExtBar.minMz

                ' tengo que ver si la model.barra es un extremo de la viga

                If b.ni = v.nudo1 Then
                    v.niN = b.EsfExtBar.nin * inve
                    v.niQy = b.EsfExtBar.niqy * inve
                    v.niQz = b.EsfExtBar.niqz * inve
                    v.niT = b.EsfExtBar.nit * inve
                    v.niMy = b.EsfExtBar.nimy
                    v.niMz = b.EsfExtBar.nimz
                Else If b.ni = v.nudo2 Then
                    v.nfN = b.EsfExtBar.nin * inve
                    v.nfQy = b.EsfExtBar.niqy * inve
                    v.nfQz = b.EsfExtBar.niqz * inve
                    v.nfT = b.EsfExtBar.nit * inve
                    v.nfMy = b.EsfExtBar.nimy
                    v.nfMz = b.EsfExtBar.nimz
                End If

                If b.nf = v.nudo1 Then
                    v.niN = b.EsfExtBar.nfn * inve
                    v.niQy = b.EsfExtBar.nfqy * inve
                    v.niQz = b.EsfExtBar.nfqz * inve
                    v.niT = b.EsfExtBar.nft * inve
                    v.niMy = b.EsfExtBar.nfmy
                    v.niMz = b.EsfExtBar.nfmz
                Else If b.nf = v.nudo2 Then
                    v.nfN = b.EsfExtBar.nfn * inve
                    v.nfQy = b.EsfExtBar.nfqy * inve
                    v.nfQz = b.EsfExtBar.nfqz * inve
                    v.nfT = b.EsfExtBar.nft * inve
                    v.nfMy = b.EsfExtBar.nfmy
                    v.nfMz = b.EsfExtBar.nfmz
                End If

            End If
        Endif

    Next

End

Public Function GetPosBar(LaViga As Integer, Xv As Float, ByRef LaBarra As Integer, ByRef Xb As Float) As Boolean

    '1 - - - - - - - - - - - - - - - - - - Xv - - - - - - - - - - - - - - - - - - - - - - - -2
    '                                         LaViga

    'i--------1------fi-----2-----fi--------Xb---3----------------fi-------------4--------------f
    '                          barras que forman la viga

    ' en este caso deberia devolver la barra=3 y Xb

    Dim Vbarras As New Integer[]
    Dim Blargos As New Float[]
    Dim Vnudos As New Integer[]

    Dim BarrasOrdenadas As New Integer[]
    Dim LargosOrdenados As New Float[]
    Dim nudoSiguiente As Integer

    Dim b As Integer, LTotal As Float
    Dim a As Integer, v As Integer

    If Xv < 0 Then Return False
    If model.vigas[LaViga].l <= 0 Then Return False

    ' primero buscamos las barras que forman la viga

    For b = 1 To model.barra.Count
        If model.barra[b].grupo = model.vigas[LaViga].grupo Then Vbarras.Add(b)

    Next

    If Vbarras.Count = 0 Then Return False  'no encontre barras que formen la viga

    ' calculo el largo
    For b = 0 To Vbarras.Max
        Blargos.Add(longitud(Vbarras[b]))
        LTotal += Blargos(b)
    Next

    If lTotal <> modAlgebra.Distancia(model.nudo[model.vigas[v].nudo1], model.nudo[model.vigas[v].nudo2]) Then
        ' no coinciden, o hay barras superpuestas
        Stop

    Endif

    ' ordeno las barras, de model.nudo 1 en adelante

    model.nudoSiguiente = model.vigas[LaViga].nudo1
    For a = 0 To Vbarras.Max
        For b = 0 To Vbarras.Max
            If model.barra[Vbarras[b]].ni = model.nudoSiguiente Then
                BarrasOrdenadas.Add(Vbarras[b])
                model.nudoSiguiente = model.barra[Vbarras[b]].nf
                Vbarras.Remove(b) ' para no repetir
                Break
            Else If model.barra[Vbarras[b]].nf = model.nudoSiguiente Then
                BarrasOrdenadas.Add(Vbarras[b])
                model.nudoSiguiente = model.barra[Vbarras[b]].ni
                Vbarras.Remove(b) ' para no repetir
                Break
            Endif
        Next
    Next

    ' aca ya estan ordenadas, entonces busco la seccion

    For a = 0 To BarrasOrdenadas.Max
        If Xv > longitud(model.barrasOrdenadas[a]) Then
            Xv -= longitud(model.barrasOrdenadas[a])
        Else 'encontre la seccion
            LaBarra = BarrasOrdenadas[a]
            Xb = Xv
            Return True
        Endif
    Next

End

Public Sub Esfuerzos_de_Barras_a_Losas(Modo As Integer)

    'coloco en model.vigas[] los esfuerzos del ultimo calculo, segun Modo
    'Modo=0 -> reemplazo los valores
    'Modo=1 -> comparo y reemplazo la peor condicion
    'Modo=2 -> Sumo los valores
    'Modo=4 -> Sumo solo si empeora la condicion

    Dim b As ClsBarra
    Dim L As ClsLosa
    Dim w As Float

    Dim frase As String

    If Not flags.calculado Then
        fmain.debugInfo("No se ha calculado el proyecto aun")
        Return
    Endif

    For Each b In model.barra ' = 1 To  model.barra.Max
        ' busco determino si pertenece a alguna losa
        If b.tipo = tipo_losa Then
            L = model.losas[b.grupo]
            If b.Eje = 1 Then w = L.dzGrid  'se divide por el otro sentido que es lo que representa la barra
            If b.Eje = 2 Then w = L.dxGrid
            If w = 0 Then w = longitud(b) ' es una aproximacion

            ' comienzo a cargar los esfuerzos
            If modo = 0 Then
                If b.Eje = 1 Then ' la model.barra corresponde a la direccion local X en la losa
                    If L.maxQx < (b.EsfExtBar.maxQy / w) Then L.maxQx = b.EsfExtBar.maxQy / w
                    If L.maxMx < (b.EsfExtBar.maxMz / w) Then
                        L.maxMx = b.EsfExtBar.maxMz / w
                        'losas[v].barra_MXmax = b  ' TODO: esto no se para q lo puse
                    End If

                    If L.minQx > (b.EsfExtBar.minQy / w) Then L.minQx = b.EsfExtBar.minQy / w
                    If L.minMx > (b.EsfExtBar.minMz / w) Then
                        L.minMx = b.EsfExtBar.minMz / w
                        'losas[v].barra_MXmin = b
                    End If
                End If

                If L.maxT < b.EsfExtBar.maxT Then L.maxT = b.EsfExtBar.maxT
                If L.minT > b.EsfExtBar.minT Then L.minT = b.EsfExtBar.minT

                If b.eje = 2 Then ' la model.barra corresponde a la direccion local Z en la losa
                    If L.maxQz < (b.EsfExtBar.maxQy / w) Then L.maxQz = b.EsfExtBar.maxQy / w
                    If L.maxMz < (b.EsfExtBar.maxMz / w) Then
                        L.maxMz = b.EsfExtBar.maxMz / w
                        'losas[v].barra_MZmax = b
                    End If
                    If L.minQz > (b.EsfExtBar.minQy / w) Then L.minQz = b.EsfExtBar.minQy / w
                    If L.minMz > (b.EsfExtBar.minMz / w) Then
                        L.minMz = b.EsfExtBar.minMz / w
                        'losas[v].barra_MZmin = b
                    End If
                End If
            Endif

        Endif

    Next

    For Each L In model.losas
        frase = frase & "Losa " & Str(L.numero) & "-" & Str(L.sector) & ":" & gb.Cr
        frase = frase & gb.Tab & "Lx" & Str(L.dxGrid) & gb.Cr
        frase = frase & gb.Tab & "Lz" & Str(L.dzGrid) & gb.Cr

        frase = frase & gb.Tab & "Mz min: " & Format(L.minMz, setting.formato) & " en model.barra " & Str(L.barra_MZmin) & gb.Cr

        fmain.debugInfo(frase)
        frase = ""

    Next

End

Public Sub Esfuerzos_de_Barras_a_Losas_en_Extremos(Modo As Integer)

    ' la diferencia conrespecto a la version 1 es que utilizo la posicion de la model.barra para ver en que parte estoy de la losa

    'coloco en model.vigas[] los esfuerzos del ultimo calculo, segun Modo
    'Modo=0 -> reemplazo los valores
    'Modo=1 -> comparo y reemplazo la peor condicion
    'Modo=2 -> Sumo los valores
    'Modo=4 -> Sumo solo si empeora la condicion

    Dim b As ClsBarra
    Dim v As ClsLosa
    Dim w As Float

    'variables de maximos
    Dim barra_MXmax As Integer
    Dim barra_MZmax As Integer
    Dim barra_MXmin As Integer
    Dim barra_MZmin As Integer

    Dim frase As String

    If Not flags.calculado Then
        fmain.debugInfo("No se ha calculado el proyecto aun")
        Return
    Endif

    For Each b In model.barra ' = 1 To  model.barra.Max
        ' busco determino si pertenece a alguna viga
        If b.tipo = tipo_losa Then
            v = model.losas[b.grupo]
            If b.Eje = 1 Then w = v.dzGrid
            If b.Eje = 2 Then w = v.dxGrid

            If w = 0 Then w = longitud(b) ' es una aproximacion

            ' comienzo a cargar los esfuerzos
            If modo = 0 Then

                If b.Eje = 1 Then ' la model.barra corresponde a la direccion local X en la losa
                    If v.maxQx < (b.EsfExtBar.maxQy / w) Then v.maxQx = b.EsfExtBar.maxQy / w
                    If v.maxMx < (b.EsfExtBar.maxMz / w) Then
                        v.maxMx = b.EsfExtBar.maxMz / w
                        v.barra_MXmax = b
                    End If

                    If v.minQx > (b.EsfExtBar.minQy / w) Then v.minQx = b.EsfExtBar.minQy / w
                    If v.minMx > (b.EsfExtBar.minMz / w) Then
                        v.minMx = b.EsfExtBar.minMz / w
                        v.barra_MXmin = b
                    End If
                End If

                If v.maxT < b.EsfExtBar.maxT Then v.maxT = b.EsfExtBar.maxT
                If v.minT > b.EsfExtBar.minT Then v.minT = b.EsfExtBar.minT

                If model.barra[b].eje = 2 Then ' la model.barra corresponde a la direccion local Z en la losa
                    If v.maxQz < (b.EsfExtBar.maxQy / w) Then v.maxQz = b.EsfExtBar.maxQy / w
                    If v.maxMz < (b.EsfExtBar.maxMz / w) Then
                        v.maxMz = b.EsfExtBar.maxMz / w
                        v.barra_MZmax = b
                    End If
                    If v.minQz > (b.EsfExtBar.minQy / w) Then v.minQz = b.EsfExtBar.minQy / w
                    If v.minMz > (b.EsfExtBar.minMz / w) Then
                        v.minMz = b.EsfExtBar.minMz / w
                        v.barra_MZmin = b
                    End If
                End If

            End If
        Endif

    Next

End

Public Function GetPosViga(grupo As String) As ClsViga

    Dim v As ClsViga

    For Each v In model.vigas
        If (v.Handle = grupo) Then Return v
    Next
    Return Null

End

Public Function GetPosLosa(grupo As String) As ClsLosa

    Dim l As ClsLosa

    For Each l In model.losas
        If (l.Handle = grupo) Then Return l
    Next
    Return Null

End

Public Function GetNodeHandle(iIndex As Integer) As String

    For Each n As ClsNudo In model.nudo
        If n.indice = iIndex Then Return n.handle
    Next

End

Public Function NewGrupo() As Integer

    Inc model.datos.TotalGrupos

    Return model.datos.TotalGrupos

End
